### ISSUE TITLE
`bench_functions` is inconsistent with `bench_function`

### ISSUE THREAD

**Issue by vks** [bheisler/criterion.rs#125]
`bench_functions` takes an input parameter while `bench_function` doesn't. I don't see why it is necessary to pass an input, because this can be trivially done with a closure. I propose to remove the input parameter to simplify the interface and improve consistency.

**Comment by bheisler** [comment]
Hey, thanks for the suggestion.

Yeah, that is unfortunate. Changing it now, however, would certainly break existing code. I don't plan to do another breaking-change release for a while.

In the meantime, you can use the `Benchmark` structure to perform comparisons between multiple functions without needing to provide an extra parameter. In that case, however, you'll need to `black_box` the parameters to your function yourself to prevent them being constant-folded.

Hope this helps!

**Comment by bheisler** [comment]
`bench_functions` is now deprecated as of 0.3.0 (in favor of the new `BenchmarkGroup` struct), so I'm going to close this.
