### ISSUE TITLE
Reports are put into incorrect directory when used in a workspace

### ISSUE THREAD

**Issue by RReverser** [bheisler/criterion.rs#192]
Say, I have a workspace with crates `crate-a` and `crate-b`. By default, Cargo will crate top-level directory `target` where it will put all build artifacts for these crates and their dependency.

However, if `crate-a` uses Criterion, it creates its own directory `crate-a/target` instead of using the directory provided by Cargo.

**Comment by bheisler** [comment]
Hey, thanks for the bug report!

Yeah, Criterion.rs should be using the `CARGO_TARGET_DIR` environment variable to find the target directory rather than hardcoding it to "./target".

**Comment by bheisler** [comment]
I can't find an environment variable that points to the correct target directory. This will have to wait until Cargo has that, or something like it.

**Comment by RReverser** [comment]
One somewhat hacky option could be to use `OUT_DIR` and determine target dir from there (either by going required number of levels up or by stopping when you find name `target`).

**Comment by RReverser** [comment]
FWIW I also tried to work around this by manually specifying `output_directory` in `Criterion` config, but, as the description says, it seems to work only for tests right now and fails on real examples.

**Comment by DianaNites** [comment]
Any update on this?

**Comment by bheisler** [comment]
No change here. Cargo will need to pass along the correct output directory, and I don't think it does.

I suppose I should send a feature request to Cargo to add that.

**Comment by DianaNites** [comment]
Did some googling and looks like it's possible with [cargo metadata](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html), and criterion already uses serde and serde_json

**Comment by AngelicosPhosphoros** [comment]
Hi!
Is the fix planned to some release? Criterion (v 0.3.3) still creates a target folder for subcrate and it's output didn't removed by `cargo clean` unfortunately.

**Comment by jolestar** [comment]
The command-line option --target-dir does not change the benchmark criterion's dir.
