### ISSUE TITLE
use custom_test_frameworks on nightly

### ISSUE THREAD

**Issue by gnzlbg** [bheisler/criterion.rs#205]
Instead of doing the whole `bench!`, `criterion_main!`, etc. on nightly, it would be nice if `criterion` would just use the `custom_test_frameworks` feature: https://github.com/rust-lang/rust/blob/master/src/doc/unstable-book/src/language-features/custom-test-frameworks.md

**Comment by bheisler** [comment]
Thanks for the suggestion. Yeah, that's the plan for the long term. My understanding is that the eRFC hasn't been implemented yet. Is that not correct?

**Comment by gnzlbg** [comment]
The RFC is already implemented AFAICT. The test crate already is
implemented on top of it.

**Comment by bheisler** [comment]
I've implemented a `#[criterion]` proc-macro using custom test frameworks in the `macro` crate; it's available in 0.3.0.
