### ISSUE TITLE
Samples take really long when profiling

### ISSUE THREAD

**Issue by djc** [bheisler/criterion.rs#206]
Hi, and thanks for working on Criterion! It's been great for my [template benchmarks](https://github.com/djc/template-benchmarks-rs).

I was trying to understood the performance differences between Askama and other template engines, and so I wanted to use Callgrind on Askama's benchmarks. However, when I do so (on my 2013-vintage MacBook Pro), the "Collecting samples" phase time blows up about 100x, such that it takes about 10 minutes for 5050 iterations:

```
djc@djc-mbp testing $ cargo bench
    Finished release [optimized] target(s) in 0.44s
     Running /Users/djc/src/askama/target/release/deps/all-736ecca55ba013b0
Benchmarking Big table: Collecting 100 samples in estimated 6.4974 s (5050 iterations)
djc@djc-mbp testing $ valgrind --tool=callgrind /Users/djc/src/askama/target/release/deps/all-736ecca55ba013b0 --bench --measure-only
[callgrind output elided]
Benchmarking Big table: Collecting 100 samples in estimated 560.24 s (5050 iterations)
```

I think (a) for profiling the sampling is not as important anyway, since the goal isn't really to compare to another run, and (b) if the run-time is so long, fewer samples is probably enough to deal with the variance?

It would be rad if Criterion would adjust the number of samples taken in a case like this (maybe contingent on `--measure-only`?), or, failing that, if there was a way to configure Criterion to take fewer samples.

**Comment by djc** [comment]
I did find that eventually -- I was looking for in the book initially, but it wasn't mentioned there. It would be nice if there was a command-line option available to do that, since for the goal of profiling vs comparison I'd really only want to reduce the sample size for the former (because it's so slow).

**Comment by bheisler** [comment]
I'm thinking of introducing a `--profile` option in 0.2.6 which iterates each benchmark a fixed number of times (or perhaps iterates until a fixed number of seconds has passed?). 

I'll probably deprecate `--measure-only` in 0.2.6 and (if nobody objects) remove it in 0.3.0. I can't think of a reason why one would want to disable the analysis but keep the usual measurement logic.

**Comment by djc** [comment]
Sounds good! I think it would make more sense to have fixed number of seconds over fixed number of times, so that a microbenchmark will still get enough samples to be somewhat reliable.
