### ISSUE TITLE
Allow multidimensional analysis

### ISSUE THREAD

**Issue by hauleth** [bheisler/criterion.rs#235]
I haven't found a way to do such thing but I have rewrite benchmarks for octavo to Criterion and I am testing functions using 2 dimensions:

- hash function
- input size

I would like to display on one graph all metrics but I would also like to compare them by separate input size, but Criterion produces them in form of tree:

![zrzut ekranu 2018-11-02 20 23 47](https://user-images.githubusercontent.com/291639/47936213-44e81800-dedd-11e8-858a-0b050e5bdbaa.png)

While I would prefer it to be matrix or similar, so when I select "overall" I have result how all functions performed in all situations, when I select single input size I can see how each function behaved within that single size, and when I select single function I can see how it behave across all input sizes.

I hope it is clear what I have in mind.

**Comment by bheisler** [comment]
Hey, thanks for the suggestion!

Yeah, I see what you mean. I agree that would be useful. Unfortunately, I haven't had much time to work on Criterion.rs lately, so I probably won't get a chance to fix it any time soon.
