### ISSUE TITLE
Do something about dead documentation links on google

### ISSUE THREAD

**Issue by anderspapitto** [bheisler/criterion.rs#248]
if I search for "rust criterion" or similar, a lot of links to this old, dead site are near the top 
https://japaric.github.io/criterion.rs/. Maybe something can be done about it?

**Comment by anderspapitto** [comment]
also on this page https://docs.rs/criterion/0.2.5/criterion/, the link to "the user guide" goes directly to that broken site.

**Comment by bheisler** [comment]
Unfortunately, I don't think there's much I can do except wait for Google to catch up. Docs.rs will be updated when I publish a new version.
