### ISSUE TITLE
add a concise output format?

### ISSUE THREAD

**Issue by anderspapitto** [bheisler/criterion.rs#249]
I'd like an option to have bencher-like output, i.e. just one line per benchmark, with just an average and maybe a bit of a range indication. If I'm focusing on an individual benchmark all of the extra information is great, but if I'm running the whole bench suite it turns into noise and makes it hard to see enough on one screen.

**Comment by anderspapitto** [comment]
I guess I can mostly get this by just running `cargo bench | grep time:`

**Comment by bheisler** [comment]
Hey, thanks for the suggestion. I think this might already be covered by #132.

**Comment by anderspapitto** [comment]
yes. I've added a comment over there with my additional thoughts
