### ISSUE TITLE
Remove `--measure-only`

### ISSUE THREAD

**Issue by bheisler** [bheisler/criterion.rs#251]
This command-line arg was deprecated in 0.2.6 and is scheduled to be removed in 0.3.0.

**Comment by Zaechus** [comment]
Hey, I can pick this up if you need.

**Comment by bheisler** [comment]
Thanks for the interest!

This issue is just here so I don't forget to do it when the time comes to start working on 0.3.0.

**Comment by Zaechus** [comment]
Are there any other issues I can do then?

**Comment by bheisler** [comment]
#185 would be suitable, or perhaps #195.
