### ISSUE TITLE
criterion-stats 0.2.6 is not compatible with 0.2.5

### ISSUE THREAD

**Issue by SimonSapin** [bheisler/criterion.rs#253]
For some reason, `cargo update` currently picks criterion 0.2.5 and criterion-stats 0.2.6 when building html5ever, but they are not compatible:

https://travis-ci.org/SimonSapin/run-nightly/builds/472880018#L1489

Cargo assumes Semantic Versioning, which says that criterion-stats 0.2.6 can be used instead of criterion-stats 0.2.5 as it is supposed to be compatible. But in this case there seems to have been a breaking API change, and so the version number should have been criterion-stats 0.3.0.

**Comment by bheisler** [comment]
Hmm. It hadn't occurred to me that Cargo might pick mismatched versions, and this has never been an issue before. There isn't really a strong reason to have criterion-stats and criterion-plot be separate crates, so I'll just merge them all into one crate in 0.3.0.

It will be a while before 0.3.0 is ready, though. In the meantime, is it acceptable to just update to 0.2.6? I'd rather not have to yank and republish, but I can if it's a major problem.

**Comment by SimonSapin** [comment]
`cargo update -p criterion --precise 0.2.6` works on my machine, but before that `cargo update` does nothing. Or, when removing `Cargo.lock`, Cargo picks 0.2.5. I don’t know why :/ The no-lock-file case is what happens on Travis-CI.

**Comment by przygienda** [comment]
yepp, it is a cardinal sin to do x.y.(z+1) and change the API signature ... This always ends in tears ... 

   Compiling criterion v0.2.5
error[E0599]: no method named `as_slice` found for type `&stats::univariate::Sample<f64>` in the current scope
  --> /Users/prz/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.2.5/src/analysis/mod.rs:99:20
   |
99 |         &(data.x().as_slice(), data.y().as_slice()),
   |                    ^^^^^^^^

**Comment by przygienda** [comment]
thanks for the update precise, that kept me going @ least ...

**Comment by turboladen** [comment]
I'm running into this as well--primarily in our CI environment at work. The workaround is fine locally, but doesn't play so well for our CI environment.

**Comment by bheisler** [comment]
Alright, seems like this is a bigger problem for folks than I thought it would be. I'll yank 0.2.6 and publish a new version.

**Comment by bheisler** [comment]
Alright, I've yanked 0.2.6 and published 0.2.7 (or 0.3.0 for `criterion-stats`). Could you folks try it again? That should have fixed it.

**Comment by turboladen** [comment]
Looks like that fixed it for me! Thanks!

**Comment by SimonSapin** [comment]
[Fixed](https://travis-ci.org/SimonSapin/run-nightly/builds/473229543) in html5ever as well, thanks!
