### ISSUE TITLE
Cannot use with project unless I downgrade `lazy_static`

### ISSUE THREAD

**Issue by novacrazy** [bheisler/criterion.rs#255]
As stated in `Cargo.toml`, `lazy_static` was limited to `1.1.0` for compatibility reasons with `rustc 1.20`.

However, It's been 16 months since `rustc 1.20` was released, and while I can appreciate backwards compatibility, it has now become a problem for forward compatibility. 

There was apparently some discussion [6-12 months ago]( #128) regarding compatibility, but did that not apply to dependencies like `lazy_static`? `lazy_static` `1.2.0` works as far back as 6-7 releases.

**Comment by bheisler** [comment]
Hey, thanks for the feedback. Unfortunately, I'm sort of stuck between a rock and a hard place on this - `bytecount` uses Criterion.rs too, and they still support 1.20 - https://github.com/llogiq/bytecount/issues/43.

**Comment by kornelski** [comment]
I've ran into this too. I can't run `cargo-outdated` on a project that has both `criterion` and `lazy_static` because it conflicts with the current version of `lazy_static`.

**Comment by bheisler** [comment]
Looks like bytecount now requires 1.27 for SIMD, so Criterion.rs 0.2.8 is clear to bump the minimum Rust version.
