### ISSUE TITLE
Roadmap for 0.3.0

### ISSUE THREAD

**Issue by bheisler** [bheisler/criterion.rs#261]
I'm planning to take some time off working on Criterion.rs shortly, but before I do I'd like to describe my plans for 0.3.0 and request some comments from the community. 0.3.0 is the first breaking-change release since Criterion.rs became stable-compatible, and I have a handful of things I'd like to change.

### Removing Benchmark/ParameterizedBenchmark

I initially created these as a generalization of the various `Criterion::bench_*` functions and they mostly work, but there are a few flaws in this design. For instance, there isn't an obvious way to handle cases like #225, where the user wants to construct a large input once. Additionally, it imposes strange limitations on the parameter types (why must they implement Debug?) and strange contortions to deal with lifetimes (#260). Additionally, sometimes the user doesn't want to have the debug representation of the parameter be used as the parameter in the benchmark ID - for example, if I'm testing a parser I don't want my benchmark to be called "my_group/my_function/Some really really long file full of text that my parser parses but isn't really relevant to the benchmark...". After thinking about this for a while, I wondered why we even need these structures at all? After all, they basically just define a nested for loop:

```rust
for function in self.functions {
    for parameter in self.parameters {
        // Run a benchmark of this function with this parameter
    }
}
```

I'm sure the user is capable of writing their own for-loops, so why not let the user provide that? Here's a sketch of what I'm thinking:

```rust
let criterion: &mut Criterion = ...;

// For simple benchmarks, the existing bench_function would still work.
criterion.bench_function("my_function", move |b| {
    b.iter(|| my_function())
}):

// Benchmark and ParameterizedBenchmark, as well as bench_functions and 
// bench_function_over_inputs would be replaced with a new BenchmarkGroup struct
let mut benchmark_group = criterion.benchmark_group("Hashes");

// The user can compare different functions by just calling bench_function multiple times
// This would produce benchmarks called "Hashes/SHA1" and "Hashes/MD5".
benchmark_group.bench_function("SHA1", |b| b.iter(|| sha1sum("some input string"));
benchmark_group.bench_function("MD5", |b| b.iter(|| md5sum("some input string"));

// `finish` would consume the benchmark group structure and generate the summary reports.
// The benchmark group could be marked `must_use` to warn people if they forget?
benchmark_group.finish();

// Handling multiple parameters is straightforward
let mut benchmark_group = criterion.benchmark_group("SizedHashes");
for input_size in vec![10, 100, 1000, 10000, 100000] {
    // Now the user can generate large inputs directly without needing support from Criterion.rs
    let input = generate_hash_input(input_size);

    // The input size can be automatically converted to String with Debug (or should it be Display?)
    // or the user can provide their own string.
    // I'm imagining some trait-magic so this could accept either a string or a BenchmarkId, so
    // that the user doesn't have to provide a fake parameter string
    benchmark_group.bench_function(BenchmarkId::new("SHA1", input_size).with_throughput(Throughput::Bytes(input_size)), |b| b.iter(|| sha1sum(input)));
    // Not totally sold on the with_throughput thing here, will need to work on that a bit more.
    benchmark_group.bench_function(BenchmarkId::new("MD5", input_size).with_throughput(Throughput::Bytes(input_size)), |b| b.iter(|| md5sum(input)));
}
benchmark_group.finish();
```

Now, this is obviously much more flexible than the current design. It would be trivial to extend this to benchmarking over multi-dimensional input spaces (just nest more for-loops) or to only benchmark certain functions for certain inputs, etc. It does put more burden on the user not to do anything silly, but I think that's reasonable. It would also require the report-generation code to be flexible enough to handle the oddball cases in a sensible way, but I don't think that will be too hard (alas, unless HTML gains the ability to describe multi-dimensional tables, I'll probably have to flatten the inputs down to one dimension for display).

This would be a pretty major breaking-change, though; nearly everyone would have to update. If I go ahead with this, I might consider deprecating the existing APIs and hiding them from the docs, which would allow existing users to continue using them.

### Preliminary Support for Custom Measurements

Criterion.rs has always measured wall-clock time, but users have been requesting other measurements (ranging from memory usage to CPU or even GPU performance counters) since before it was even released. I've been putting it off until I thought of a decent design, but I think I have one now. I'm thinking of something like this:

```rust
trait Measurement {
    type Intermediate;
    type Value;
    type Analysis: Analysis<Self::Value>;
    type Report: Report<Self::Analysis::Output>;

    fn start() -> Self::Intermediate;
    fn end(i: Self::Intermediate) -> Self::Value;
    // Probably some more functions to perform analysis and generate the report(s)
}

struct WallTime;
impl Measurement for Walltime {
    type Intermediate = Instant;
    type Value = Duration;
    type Analysis = TimeAnalysis;
    type Report = StatisticalReport;

    fn start() -> Instant { Instant::now() }
    fn end(i: Instant) -> Duration { i.elapsed() }
}

// For example...
struct MemoryUsage;
impl Measurement for MemoryUsage {
    type Intermediate = Bytes;
    type Value = BytesDifference;
    type Analysis = MemoryAnalysis;
    type Report = SingleValueReport;

    fn start() -> Bytes { get_bytes_allocated() };
    fn end(b: Bytes) -> BytesDifference { get_bytes_allocated() - b  }
}
```

The Criterion and Bencher structs would then gain a new type parameter `M: Measurement`, defaulting to `WallTime`. Some way to obtain a `Criterion<MemoryUsage>` would be needed as well; I'm not totally sure what that would look like.

I like this traits-and-types approach for a few reasons. It means that the measurements are statically known and can be inlined to reduce measurement overhead. It means that measurements can be defined in third-party crates, or customized by the user. It also means that I can gate functions in the Bencher on different measurements - the `Bencher::iter_*` family don't really make sense for mostly-constant measurements like memory allocated in an iteration of a function, so maybe those would only be defined for some measurement types

To start with, the analysis and report traits would probably be hidden and sealed to give me some more time to pin down their definitions, but this would allow various other timing measurements to be defined and analyzed/reported with the same code that handles the wall-clock measurements.

### Custom "Test" Framework

I'm not sure if I'll do this for 0.3.0 at launch or at some point after, but now that custom test framework proc-macros are available in nightly Criterion.rs should add support for them. If we need any breaking changes for ergonomic usage of a `#[criterion]` macro, I should figure out what they are and make them in 0.3.0.

### Misc.

There's a variety of other, smaller breakages listed under the [Breaking Changes](https://github.com/bheisler/criterion.rs/issues?q=is%3Aissue+is%3Aopen+label%3A%22Breaking+Change%22) issue label. Mostly they're for removing deprecated things and/or disallowing legal-but-probably-wrong values to various functions.

Notably, external-program benchmarks will be removed, but they've been deprecated for several versions now and nobody has complained. I'm guessing nobody actually uses those.

----

Alright, that's all I've got. Comments or ideas would be welcome.

**Comment by AdamBrouwersHarries** [comment]
> Preliminary Support for Custom Measurements

This would be very very welcome! I have a couple of benchmarks where I want to also measure the accuracy, so being able to track both (I currently only track runtime) would be very useful.

> Removing Benchmark/ParameterizedBenchmark

I'm less of a fan of this - I've been using parameterized benchmarks quite happily with very large inputs. My "trick" is to have a global state, which I lazily load at the start of each benchmark (before iterating), and cache the results. In each benchmark, I use the parameter to lookup a reference to the specific bit of data (a vector of f32 values), which is then fed to the function in the benchmark. A slightly more formal version of this method might be better? E.g. with criterion providing a state-manager of some sort, with optional methods to initialise it before benchmarks, and provide lookups given a parameter. If you want to see how I've done it (warning: lots of unsafe code), take a look here: https://github.com/AdamHarries/simple_bpm/blob/master/benches/performance_tests.rs

Thanks for all your work on criterion by the way, it's wonderfully high quality, and very, very useful!

**Comment by bheisler** [comment]
Hey, thanks for the comment. 

What exactly do you mean by accuracy? Non-timing measurements probably wouldn't be supported right away, but I think if I get the design right I should be able to support things like memory usage measurements later on without too much trouble. If so, that could probably be extended to other things.

Maybe "removing ParameterizedBenchmark" is too harsh - I'd probably deprecate it instead, or maybe just hide it from the documentation to encourage new benchmarks to use the newer method but allow existing code to continue working. It seems like the interface I outlined would allow for the same capability without requiring Criterion.rs to provide a state manager or the user to write custom unsafe code.

**Comment by AdamBrouwersHarries** [comment]
> What exactly do you mean by accuracy

Apologies - I wasn't very clear with this sentence. I've got a routine that calculates a value for a stream of audio data (specifically, the tempo), which has varying wallclock performance depending on the parameters with which you configure it (e.g. # of samples, buffer size, etc). These samples also determine the accuracy of the algorithm wrt some ground truth BPM value, so I would be interested in tracking that as well as the wallclock time of the algorithm. That way, I'd be able to (e.g.) plot time vs accuracy, or verify that well performing parameters don't reduce the accuracy too much. 

> Non-timing measurements probably wouldn't be supported right away 

Just my 2c, but I'd suggest treating all "measurements" fairly equally (aside from the wallclock time that criterion measures). That way you don't need to have different systems for managing each kind of measurements. I'd suggest looking at how googlebench does it: https://github.com/google/benchmark. We use them at work, and rely on the ability to measure a) wallclock time, and b) GPU execution time, from OpenCL profiling information. 

There is a potential question as to how statistical information should be reported for non-timing benchmarks, but I think it should be possible to have that user-configurable as well. For example, for GPU kernel time, it's sometimes useful to look at the min execution time, as it gives you the peak throughput that you might expect. 

> Removing ParameterizedBenchmark

I'm a little confused by the interface that you outlined/sketched above. Would that be code that users wrote in a main() function? If so, I think it seems relatively good, and gives more or less the same power that we have now, with the loss of a little bit of structured cleanliness, but not tooo much :)

**Comment by Licenser** [comment]
I read over the suggestion and I got two thoughts so far. Basically, everything non derived is a counter (of one thing or another), of nanoseconds, of bytes, of allocations, of CPU cycles, etc. The derived metrics come into play with throughput/counter (this can be interesting beyond time. for simdjson cycles/byte is an interesting measurement). So could be all analysis be generalized?

The second thing I was wondering if it wouldn't make sense to allow combining measurements - thinking of perf counters I think having all of them in 1 go, despite the slight overhead that adds, is more useful then having results from different measurements - plus it dramatically reduces the test times if you need a hand full of different counters.

**Comment by bheisler** [comment]
I'm not sure about generalizing the analysis, but I had intended to allow for plugging in different analyses as well; whatever is appropriate for the measurement. Note though, that feature wouldn't be in 0.3.0, I just wanted to note it down for later.

As for combining measurements; That probably wouldn't be supported by 0.3.0 (or only supported in a very limited way) but I expect it could be added in later versions.

**Comment by rubdos** [comment]
FWIW, the new roll-your-own-loop proposal would allow to compare functions with an input range, so that would elegantly fix #299 for me.

**Comment by rubdos** [comment]
Maybe it is also useful to think about how criterion should support multi-dimensional input data? Just mapping BenchmarkId("name", a, b, c) to "name-a/b/c" should suffice in the beginning, but I think the API could be there already.

**Comment by bheisler** [comment]
0.3.0 is now released. Closing this issue.
