### ISSUE TITLE
Feature request: Run a function after warmup completes

### ISSUE THREAD

**Issue by thomcc** [bheisler/criterion.rs#264]
We're using criterion to benchmark some SQL queries, it would nice to be able to run `PRAGMA optimize` after the warmup completes so that the database can be optimized (in particular, indices and tables can be analyzed).

**Comment by bheisler** [comment]
Hey, thanks for the suggestion.

I think I understand what you're getting at, but your proposed solution is not quite right.. Criterion.rs does make the assumption that the warmup is doing the same amount of work as the real benchmark, and this would break that assumption.

I would recommend manually priming the database before calling the benchmark. This does have the slight drawback that the priming process will be executed even if the benchmark itself is disabled.

Hope this helps!
