### ISSUE TITLE
Weird: my benchmark slows by half when I add two benchmarks instead of one

### ISSUE THREAD

**Issue by velvia** [bheisler/criterion.rs#268]
Has anyone seen this?

I have two benchmarks currently using `bench_function_over_inputs` which run in the 10-20ns range.  When I include just one of the benchmarks, it runs on average around 10ns.  But when I include both benchmarks, then each one runs in 20ns - that is the time for the same benchmark doubles!  

```
criterion_group!(benches, benchmark_a, benchmark_b);
criterion_main!(benches);
```

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs. That's definitely unexpected - could you share the rest of your benchmark code?

**Comment by velvia** [comment]
@bheisler I'll see if I can share it, may take a week or two.  
I have discovered it matters which type of benchmark I mix together.
So far I love Criterion by the way - it totally satisfies specific needs including benchmarking with variable input, and easy integration with profiling tools (basically with --profile-time).   I wish could integrate `cargo-with` into `cargo bench`.

**Comment by bheisler** [comment]
If you could create an artificial benchmark that produces this problem as well, that would help as well - then there wouldn't be any problems with sharing private code.

I'm glad you like it! It may be worth asking the maintainers of cargo and cargo-with about better integration.

**Comment by bheisler** [comment]
Hey, has there been any change on this?

**Comment by TomGillen** [comment]
I am seeing something perhaps similar. I have a two benchmarks which individually complete in about 2us if the other is commented out, but take 6us if they both exist. The two benchmarks test two paths through the same piece of code, and there is no state shared between them (and the first benchmark slows down even though the second has not yet began execution).

It has gotten to the point where the only thing I can think of to explain this is that I am falling foul of some kind of LLVM optimizer corner case, like it is deciding to _not_ inline something important if the code is used in more than one location - even though it is all marked up with `#[inline]`.

**Comment by TomGillen** [comment]
I just went back through my code, and found a couple places missing an #[inline] and, even though they were trivial functions only called once per benchmark, the performance difference disapeared. So it looks like I _was_ running into a case of the compiler deciding to not inline some performance-critical code.

@velvia Perhaps your issue has the same cause?

**Comment by bheisler** [comment]
Closing this as resolved; if you still have this issue feel free to reopen it.
