### ISSUE TITLE
criterion mixes baselines for benchmarks with identical first 65 characters

### ISSUE THREAD

**Issue by pierrechevalier83** [bheisler/criterion.rs#272]
I've made a minimal repro in this repo:
https://github.com/pierrechevalier83/criterion_truncation_bug

As mentioned in that repo:
Given 2 benchmarks with very long names that start with the same sequence of letters, the first benchmark is taken as a baseline for the second one.

To reproduce the bug,

```
git clone git@github.com:pierrechevalier83/criterion_truncation_bug.git
cd criterion_truncation_bug
cargo bench
```
Output:
```
a_bench_with_an_obnoxiously_ridiculously_amazingly_stupidly_long_name_fast
                        time:   [1.4338 ns 1.4368 ns 1.4402 ns]
Found 8 outliers among 100 measurements (8.00%)
  1 (1.00%) low mild
  2 (2.00%) high mild
  5 (5.00%) high severe

a_bench_with_an_obnoxiously_ridiculously_amazingly_stupidly_long_name_slow
                        time:   [1.1065 ms 1.1093 ms 1.1123 ms]
                        change: [+76366352% +76777977% +77145093%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) low mild
```

Observe that the name was truncated at 65 characters in the report folder, leading to the confusion:

```
ls target/criterion
a_bench_with_an_obnoxiously_ridiculously_amazingly_stupidly_long  report
```

Note that this is related to https://github.com/bheisler/criterion.rs/issues/120 but not a duplicate.

**Comment by pierrechevalier83** [comment]
It actually looks pretty intentional when reading report.rs:
```
const MAX_DIRECTORY_NAME_LEN: usize = 64;
```
https://github.com/bheisler/criterion.rs/blob/b1ef65cbe4c36075b45aea2996db1f1ec3614676/src/report.rs#L91

Maybe the best thing to do would be to detect multiple benchmarks with the first MAX_DIRECTORY_NAME_LEN characters in common and report an error so the user isn't surprised.

**Comment by bheisler** [comment]
Hey, thanks for the bug report and thanks for trying Criterion.rs.

That's definitely not intended. The 64-character cutoff is supposed to prevent Criterion.rs from generating invalid file paths (some systems limit the length of folder names). It's supposed to attach an `_2` or similar to make them different.

**Comment by pierrechevalier83** [comment]
Thanks @bheisler! I really enjoy using criterion, btw: it's really intuitive to use and is super useful. We use it at maidsafe for benchmarking one of our crates: Parsec and we love it :smile:

With the hint you gave, I identified the root cause of the problem and raised [a PR](https://github.com/bheisler/criterion.rs/pull/277).

Thanks for maintaining this awesome crate :smile:
