### ISSUE TITLE
Integrate Flame Support

### ISSUE THREAD

**Issue by ChosunOne** [bheisler/criterion.rs#274]
This is pretty much just a feature request, but it would be great to implement flame graphs with criterion.  There are a few flame libraries that could get it started, but I love the idea of criterion benches being an almost one-stop shop for profiling in Rust.  

Flame graphs combined with the statistical measurements of criterion just seems like a match too good to ignore.

**Comment by bheisler** [comment]
Hey, thanks for the suggestion.

Incorporating profiling into Criterion.rs itself is definitely out-of-scope for this project. However, there is a cargo subcommand to run binaries in a profiler and generate a flamegraph - [cargo-flamegraph](https://github.com/ferrous-systems/cargo-flamegraph). That, combined with Criterion.rs' profiling mode should do what you're looking for.
