### ISSUE TITLE
`--save-baseline` error

### ISSUE THREAD

**Issue by KillTheMule** [bheisler/criterion.rs#275]
Hey!

I've seen https://github.com/bheisler/criterion.rs/blob/master/book/src/faq.md#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options, and I've edited my [`Cargo.toml`](https://github.com/KillTheMule/nvimpam/blob/impro/Cargo.toml#L40) accordingly. However, I still get the error about an unrecognized command line option when trying to save the benchmark result with `--save-baseline`. Anything I'm missing here? Is this still supposed to work as of criterion 0.2.10? If I should provide more info, let me know what. Thanks :)

**Comment by KillTheMule** [comment]
~~Funny how things happen at the same time... you might want to add a note to the faq that states that this only works on edition 2018. Turns out I wasn't using it accidentally (needs to be enabled explicitely in `Cargo.toml`), and since I noticed that today and switched, I noticed the error going away.~~

**Comment by KillTheMule** [comment]
Turns out the error reappears after the compilation of the benchmark was done, I posted to soon. Sorry for that noise, the problem persists!

**Comment by bheisler** [comment]
Hey, thanks for the bug report. This ought to work. I just tested it and it does work for me; could you share the exact command you're running?

**Comment by KillTheMule** [comment]
Sure: `cargo bench -- --save-baseline first`. The repository I linked it at the exact commit btw.

**Comment by maoe** [comment]
I had the same issue. Does adding this bit in Cargo.toml help?

```toml
[lib]
bench = false
```

EDIT: Sorry it's already in your Cargo.toml. Never mind.

**Comment by bheisler** [comment]
Hey, thanks for your patience on this.

I was able to track down the problem. Your project produces a binary as well as a library, and when Cargo automatically discovers the binary target at `src/bin/nvimpam.rs` it enables the default benchmarking harness for that for some reason.

If I add this to your Cargo.toml then it seems to work:

```toml
[[bin]]
name = "nvimpam"
path = "src/bin/nvimpam.rs"
bench = false
```

**Comment by KillTheMule** [comment]
Abso-frickin-lutely awesome! Thanks a LOT for figuring this out, works as advertised!

**Comment by mwillsey** [comment]
I just ran into this with criterion 0.3.4 on a library with no binaries. Adding this fixed it.
```toml
[lib]
bench = false
```

Maybe worth adding to the Getting Started guide.
