### ISSUE TITLE
Output gnuplot script for further modification

### ISSUE THREAD

**Issue by magneticflux-** [bheisler/criterion.rs#279]
I want to be able to modify the script output to include best fit lines. This is possible in gnuplot, but the functionality is not exposed.

Edit: Another option would be to export another CSV that includes the points which would be plotted, so an external plotter can be used.

**Comment by bheisler** [comment]
Hey, thanks for the idea, and thanks for trying Criterion.rs!

This isn't really an officially-supported feature, but if you run your benchmarks with [debug output](https://bheisler.github.io/criterion.rs/book/index.html#debug-output) enabled Criterion will save the gnuplot scripts next to the generated plots.

**Comment by magneticflux-** [comment]
@bheisler Awesome, thanks for the workaround and thanks for this tool!

Feel free to close this issue unless you want to use it to track a feature.
