### ISSUE TITLE
`fibonacci` example in README is optimized away/completely constant folded

### ISSUE THREAD

**Issue by LukasKalbertodt** [bheisler/criterion.rs#280]
I just tried the Fibonacci example from the README and was delighted that my CPU was able to calculate the 20th Fibonacci number in only 300 picoseconds! Once I changed the example to `fibonacci(black_box(20))` (with `real_blackbox` enabled), I got a performance regression by +5975852% :(

`rustc 1.35.0-nightly (0633c55d2 2019-03-23)` in case anyone want to test this too. The example should probably use `black_box` too. I'm a bit confused though, because [it is not constant folded on Godbolt](https://rust.godbolt.org/z/iehxuM). Mh.

**Comment by bheisler** [comment]
Blasted LLVM, keeps getting smart enough to mess up my lovely benchmarks. 😉 

Thanks for letting me know, I'll fix that.
