### ISSUE TITLE
Lower compile times

### ISSUE THREAD

**Issue by ghost** [bheisler/criterion.rs#281]
Have you considered prioritizing lower compile times? #266 would appear to be a good step in that direction but I see it‘s not part of #261 (although some of the breaking changes do remove features).

(Thanks for maintaining Criterion! It‘s a fundamental component of Rust‘s present and future.)

**Comment by bheisler** [comment]
Hey, thanks for the suggestion and the kind words.

I've already done a bunch of work to reduce Criterion.rs' dependency tree for this exact reason. Unfortunately, I don't think there's much room left for improvement here. Most of Criterion.rs' dependencies are more-or-less necessary for core functionality. Major dependency subgraphs come from `rayon` (used to speed up analysis of measurements), `serde` (used to persist measurements to disk) and `rand` (used in analyzing measurements) - and I've already cut those down as much as I can. Offloading the report generation to a second binary actually wouldn't help compile times that much, I'm afraid.

I think we have to wait for rustc to gradually get faster.
