### ISSUE TITLE
ParameterizedBenchmark lables look weird

### ISSUE THREAD

**Issue by dvdplm** [bheisler/criterion.rs#287]
My benchmark uses `ParameterizedBenchmark` with random byte slices of different lengths as input. When the benchmark runs it prints strings on the form group_id/id/<random byte slice> and it looks quite terrible, e.g. `something/blabla/([78, 110, 104, 83, 84, 77, 52, 72, 86, 67, 105, 108, 108, 86, 53, 112, 10...`.

Is there any way around this currently? Planned?

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs.

Yeah, the current interface doesn't handle this use case super-well. That's one of the benefits of the revised design I presented in #261, but I have no idea when I'll get around to actually implementing it.

In the meantime, there are a couple of workarounds. One option is to wrap your byte slices in a newtype which implements `Debug` to print the length of the slice. The other option is to parameterize your benchmarks on the length of the byte slices and generate the slices themselves in the per-sample setup like so:

```rust
ParameterizedBenchmark::new(
    "name",
    |b, length| {
        let bytes = generate_bytes(length);
        b.iter(|| {
            // Code to benchmark goes here
        }
    }),
    vec![1usize, 10, 100, 1000, 10000]
)
```

**Comment by bheisler** [comment]
The new `BenchmarkGroup` struct in 0.3.0 allows the caller to provide their own string for the benchmark ID independently of the parameter's value. I'm going to close this for now, please re-open if that doesn't suit your needs.
