### ISSUE TITLE
Running a single benchmark (out of many)

### ISSUE THREAD

**Issue by lostman** [bheisler/criterion.rs#291]
I have a single module `benches/my_benches.rs` that defines multiple Criterion benchmarks. I would like to be able to run them one at a time. Is this possible?

I tried:
```
cargo bench --bench NAME
```
But it only works for the whole module. I can always split my benchmarks into multiple modules but that's a less-desirable solution.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs. Criterion.rs supports the same filtering behavior that the standard-library testing and benchmarking tools support, so you should be able to just run `cargo bench NAME` and it will only run benchmarks with "NAME" in the benchmark name or function name.

**Comment by lostman** [comment]
@bheisler ah, you're right! Thank you.
