### ISSUE TITLE
How to best cite this library?

### ISSUE THREAD

**Issue by LukasKalbertodt** [bheisler/criterion.rs#293]
I used Criterion for my master thesis and I would like to cite it. Of course I could simply cite with the link to this GitHub project. But maybe you have a preferred way of being cited? Maybe you could put bibtex code somewhere in the user guide?

**Comment by bheisler** [comment]
Huh. That's... not something I'd ever considered before. I don't really know much about how citations work in academia, so I have no strong opinions on this. I'd think a link to GitHub should be fine.

It's kind of awesome that you're using Criterion.rs for something like that though. I'd love to read your thesis if/when it's available. What's it about?

**Comment by LukasKalbertodt** [comment]
> I don't really know much about how citations work in academia

Me neither, but just to give some examples (I came accross):
- CGAL has a fairly interesting model where they treat different modules of the library (particularly their documentations) as publications that can be cited. They provide bibtex entries: https://doc.cgal.org/latest/Manual/how_to_cite_cgal.html
- Some libraries, like [OpenMesh](https://www.openmesh.org), are cited by citing the paper that introduced them (Botsch, Mario, et al. "Openmesh-a generic and efficient polygon mesh data structure." (2002). in this case). I guess there are no publications introducing criterion?
- PMP expects users to simply cite their website, but they also provide a bibtex entry here: https://www.pmp-library.org/ (at the bottom of the page, "Acknowledgments")

So apparently there is not "the way to do it". For now I will simply cite this GitHub repo, as you said. You still have roughly 2 weeks left to change your mind ;-) I will stay subscribed to this thread.

> It's kind of awesome that you're using Criterion.rs for something like that though. I'd love to read your thesis if/when it's available. What's it about?

It's nothing special really. As the examples above indicated, my thesis is in the field of geometry processing. I'm basically writing a Rust library for geometry processing (and more) and try to "beat" established libraries such as OpenMesh (mostly in terms of speed). I'm still not 100% clear how many benchmarks I will actually do with criterion, but at least one big criterion benchmark will be in the thesis. 

I will publish the library and the thesis in a couple of weeks, both open source. I can ping this thread, if you want.

**Comment by rubdos** [comment]
FWIW, my master thesis from a year ago reads "Aparicio, J., & Heisler, B. (2014–2018). criterion.rs: Statistics-driven micro-benchmarking library. Retrieved June 17, 2018, from https://github.com/japaric/criterion.rs".  I cited in APA style. Maybe @bheisler should've been "first author", but not sure there.

**Comment by LukasKalbertodt** [comment]
@rubdos Thanks for your input! I guess adding the main authors is a good idea, even in an OpenSource project. I chose @bheisler as first author, because they are listed first [here](https://github.com/bheisler/criterion.rs/graphs/contributors).

I will use the following bibtex entry now (*note*: I don't know a lot about bibtex or about citations!)

```
@online{criterion,
  author = {Brook Heisler and Jorge Aparicio},
  title = {Criterion: statistics-driven micro-benchmarking library},
  year = {2014--2019},
  url = {https://github.com/bheisler/criterion.rs},
  urldate = {FILL}
}
```

**Comment by rubdos** [comment]
> @rubdos Thanks for your input! I guess adding the main authors is a good idea, even in an OpenSource project. I chose @bheisler as first author, because they are listed first [here](https://github.com/bheisler/criterion.rs/graphs/contributors).

Yeh, "first" is a bit interpretable. I had Aparicio first, because he was the one that seems to have started it off (if you look at the contributions, it's still visible).

I had 

```bibtex
@misc{criterion.rs,
  title={{criterion.rs: Statistics-driven micro-benchmarking library}},
  author={Jorge Aparicio and Brook Heisler},
  url={https://github.com/japaric/criterion.rs},
  urldate={2018-06-17},
  year={2014--2018},
}
```

So that's quite close. `urldate` should probably be the day you add it to your `.bib`.

**Comment by bheisler** [comment]
Yeah, I would list japaric as the primary author. He initially built most of what is now Criterion.rs, then I polished it up afterwards and released it.

**Comment by LukasKalbertodt** [comment]
@bheisler I put japaric first now, a few hours before printing :grin: 

My thesis is now public: https://github.com/LukasKalbertodt/masters-thesis (PDF link in the README). The part I used Criterion for is the "'Array of Structs' vs. 'Struct of Arrays'" subsection on pages 30 to 34. I don't know if this is of any interest to you, but I wanted to post this here since you asked for it.

Regarding this issue: I guess this can be closed?

**Comment by bheisler** [comment]
That is awesome. Thanks for letting me know!

**Comment by rubdos** [comment]
Oh, if we're doing theses: [here's mine](https://rubdos.gitlab.io/msc-thesis/main.pdf). I used criterion for the graphs on page 45, which is of course already old data.

[The paper that came after](https://link.springer.com/chapter/10.1007/978-3-030-16744-8_9) contains more recent data ([pre-print here](https://rubdos.gitlab.io/papers/ifip-ss-2018.pdf)). I now see that I did not cite Criterion.rs as well as I did for the thesis... I only mentioned it without properly referring :disappointed:
