### ISSUE TITLE
measurement_time is not respected

### ISSUE THREAD

**Issue by danburkert** [bheisler/criterion.rs#295]
Hi, I'm running some benchmarks where some cases have an iteration time on the order of a few seconds, and criterion benchmarks are estimated to take upwards of 30 minutes.  I've tried tuning the `measurement_time` config down to 500ms, but it seemingly has no effect:

```
Benchmarking google_message4/encode: Collecting 100 samples in estimated 1799.8 s (5050 iterations)
```

Am I misunderstanding the tunable?  Reducing `sample_size` to something smaller like 10 does work, but my test cases are somewhat all over the map in terms of how long they take to run, so I'd prefer to limit by time instead of by samples/iterations if possible.

Last but not least, thanks for the excellent library.

**Comment by danburkert** [comment]
I believe it's also the case that the default `measurement_time` of 5s is not respected, since 5050 iterations seems to be the minimum in practice (without tuning `sample_size`).

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs.

Yes, this is expected. The sample count trumps measurement time. This is a necessary consequence of how Criterion.rs performs its analysis, which relies on taking many samples where each sample contains an increasing number of iterations. It tries to scale the number of iterations to fit your desired measurement time, but sometimes this is just not possible. In this case, a measurement of 1+2+3+...+100 iterations gives a total iteration count of 5050.

My main recommendation would be to reduce the size of your benchmark if at all possible. If it isn't possible, reducing the sample count is probably the way to go; for such a large benchmark you shouldn't need a lot of statistical resolution to detect changes in performance. It may be helpful to separate your benchmarks into slow and fast groups with different sample counts, or use the `Benchmark` struct to set sample counts on a per-benchmark basis.

**Comment by bheisler** [comment]
Closing - working as expected.
