### ISSUE TITLE
New to rust, trying to use bench_function_over_inputs

### ISSUE THREAD

**Issue by veniamin-ilmer** [bheisler/criterion.rs#298]
I got excited about criterion having a `bench_function_over_inputs`, unlike bencher.

I am trying to test how well bubble sort works when used against 4 different types of data:

* Baseline (1 value. Nothing to sort.)
* Sorted
* Reverse sorted
* Random

Here is my code:

    use criterion::Criterion;
    use criterion::black_box;

    use rand::thread_rng;
    use rand::seq::SliceRandom;

    fn sort(in_vec: &mut [u32]) {
    	let mut n = in_vec.len();
    	while n > 1 {	//When n gets to 1 that means there was nothing left to swap. It's an efficient way to check that everything is in order.
    		let mut new_n = 0;
    		for i in 1..n {
    			if in_vec[i - 1] > in_vec[i] {
    				in_vec.swap(i - 1, i);
    				new_n = i;
    			}
    		}
    		n = new_n;
    	}
    }

    pub fn bench(c: &mut Criterion) {
    	let mut random_vec: Vec<u32> = (0..10_000).collect();
    	random_vec.shuffle(&mut thread_rng());

    	c.bench_function_over_inputs("bubble_sort", |b, in_vec| b.iter(|| {
    		let mut in_vec = black_box(in_vec);
    		sort(&mut in_vec);
    	}),
    	&[
    		(0..1).collect(),
    		(0..10_000).collect(),
    		(0..10_000).rev().collect(),
    		random_vec,
    	]);
    }

I get an error:

    error[E0596]: cannot borrow data in a `&` reference as mutable
      --> benches/sort\_bubble_sort.rs:27:8
       |
    27 |         sort(&mut in_vec);
       |              ^^^^^^^^^^^^ cannot borrow as mutable

    error[E0716]: temporary value dropped while borrowed
      --> benches/sort\_bubble_sort.rs:29:3
       |
    25 |        c.bench_function_over_inputs("bubble_sort", |b, in_vec| b.iter(|| {
       |   _____-
    26 |  |         let mut in_vec = black_box(in_vec);
    27 |  |         sort(&mut in_vec);
    28 |  |     }),
    29 |  |     &[
       |  |______^
    30 | ||         (0..1).collect(),
    31 | ||         (0..10_000).collect(),
    32 | ||         (0..10_000).rev().collect(),
    33 | ||         random_vec,
    34 | ||     ]);
       | ||     ^-- temporary value is freed at the end of this statement
       | ||_____||
       | |______|argument requires that borrow lasts for `'static`
       |        creates a temporary which is freed while still in use

Do you know how I can fix this?

**Comment by Eh2406** [comment]
So in the first `b.iter` of your benchmark `in_vec` is sorted in place. What do you want to happen in subsequent calls to `b.iter`?

**Comment by veniamin-ilmer** [comment]
I want the fact that I sorted in_vec to be forgotten, for in_vec to be restored back to what it was when it was sent into the function.

**Comment by Eh2406** [comment]
So if you want it to be restored back then someplace in memory will need to hold the original, and some time needs to be spent to do the copying.

The smallest diff is
```rust
		let mut in_vec = black_box(in_vec.clone());
```
`clone` allocates a new spot in the heap, copies the contents of `in_vec`, and returns the new version.
This works, and is probably what I would use. But allocation is noizy it does not always take the same amount of time, so if you need this benchmark to have less variance, then:
```rust
	c.bench_function_over_inputs("bubble_sort", |b, in_vec| {
                let mut mut_vec = in_vec.clone(); // allocates a new spot in the heap
		b.iter(|| {
                        mut_vec.clear(); // remove the content without changing the allocations
                        mut_vec.extend_from_slice(&in_vec) // put the original content back in
			black_box(mut_vec);
			sort(&mut mut_vec);
		}),
	},
```
(have not run it, there may be a lifetime problem)
This version does not measure the time to do the allocation. It is still including the time for copying all the content. Copying numbers is fairly constant time, and faster then the sort. So this is a very good solution for your case. But let's say you were using Strings or something else where copying the content is not cheap. Or let's say you were benchmarking binary search inset, or something else much faster then the copying. Or for some reason you really needed to know the time in `sort` without the small copying overhead.
Then you may have to look at setting up all the `mut_vec`s in advance before the timing loop starts. There is an API for this:
https://docs.rs/criterion/0.2.11/criterion/struct.Bencher.html#method.iter_batched
and its example is benchmarking a sort function. Something like:
```rust
	c.bench_function_over_inputs("bubble_sort", |b, in_vec| b.iter_batched(
        || in_vec.clone(),
        |mut mut_vec| {
		let mut mut_vec= black_box(mut_vec);
		sort(&mut mut_vec);
	}),
```

**Comment by veniamin-ilmer** [comment]
Thank you very much!

This has been very informative.

I am actively using the function iter_batched now.

I also have discovered your log graph functionality, which really helped me as well.

You put a lot of good effort into this project!

Thank you!

**Comment by Eh2406** [comment]
I am glad to be informative.

I agree that it is a great project. I wish I could claim to be involved in it.

**Comment by bheisler** [comment]
Hey, thanks for helping out, @Eh2406.
