### ISSUE TITLE
bench_functions: input range

### ISSUE THREAD

**Issue by rubdos** [bheisler/criterion.rs#299]
`ParameterizedBenchmark` currently accepts multiple function to be tested over a common range.

I have a scenario where I have N (pairs of) functions, and it would be nice if I could do

```rust
let bench = ParameterizedBenchmark::with_functions(funs, range);
```

instead of (shortened)

```rust
let mut bench = ParameterizedBenchmark::new("name", funs.pop().unwrap(), range);
for fun in funs {
    bench = ParameterizedBenchmark::new("name", fun, range);
}
```

This `with_functions` method exists, but is currently `pub(crate)`.

---

I see that `Criterion::bench_functions` should be able to do this, but its input parameter only takes a single value. #125 is probably related, since there it is asked to remove the input.

**Comment by bheisler** [comment]
Hey, thanks for the suggestion.

I currently plan to significantly change how ParameterizedBenchmark and friends work - I think the plans outlined in #261 should help with this. Could you take a look at those plans and let me know what you think?

**Comment by rubdos** [comment]
The new design you propose in #261 indeed seems to fix this. I'll drop a comment there regarding this issue, so that #261 doesn't lose track of this.
