### ISSUE TITLE
Compare functions with slightly different inputs

### ISSUE THREAD

**Issue by jplatte** [bheisler/criterion.rs#303]
I am benchmarking two functions with criterion. Generally, the runtime increases with the input value, and function 2 is faster than function 1. However, function 2 doesn't allow a range of small input values that function 1 does allow. I would like filter out these inputs for function 2, but still run function 1 with them.

To give another motivation, filtering inputs is also useful if comparing more than two functions where two of them are substantially faster than the others and their difference is hard to see in a plot of the whole group.

I'd be happy to implement this myself, if such a feature is deemed useful.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs!

This particular use-case isn't supported right now, but 0.3.0 will add support for this. See the plans in #261 for more details.

**Comment by bheisler** [comment]
This should be doable now with the `BenchmarkGroup` struct in 0.3.0. Closing for now, please re-open if that doesn't suit your needs.
