### ISSUE TITLE
Is there a way to bench a function that runs very slow?

### ISSUE THREAD

**Issue by liufuyang** [bheisler/criterion.rs#306]
For example I have a function that might take 1 minutes to finish running, is there a way to bench a function to only let it run once or twice?

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs.

Unfortunately, for this use-case Criterion.rs may not be the best solution (or at least, not as it is now). If you have very long-running benchmarks you probably don't need clever statistics to determine if you've improved or regressed the performance of your code, you can just run it under `/usr/bin/time` and look at the numbers. Or, alternately, roll your own very simple "benchmarking framework" by just calling `Instant::now()` before and after calling your minute-long function.

With that said, it is inconvenient to have to have two separate classes of benchmarks; it would be nice to be able to include slow benchmarks in Criterion.rs' reports and similar. I do plan to improve Criterion.rs' support for this use case, but it's not currently a priority. It won't be available for quite some time.

**Comment by liufuyang** [comment]
Thank you for your input. I think it totally makes sense :)
