### ISSUE TITLE
add more arguments related to Criterion

### ISSUE THREAD

**Issue by YangKeao** [bheisler/criterion.rs#311]
`configure_from_args` method will collect arguments from command line and set some arguments. But there are still many arguments which can not be set with command line arguments such as `warm_up_time` and `measurement_time`.

We can add `--warm-up-time` and `--measurement-time` arguments (with default unit "second") to set them. It will improve user experience significantly (at least for me) with little effort.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs and thanks for the suggestion!

This seems like a reasonable idea to me. I'm a bit curious why you need to change the warm-up-time and measurement-time so often, though.

**Comment by YangKeao** [comment]
@bheisler Under some situations, bench scripts project and the project itself are seperated. I think configuring `warm_up_time` and `measurement_time` should be part of responsibility of bench scripts but not the project itself.

So that any attempt in changing `warm_up_time` and `measurement_time` to get a more meaningful result could be a commit/PR in bench script repo.

[PR](https://github.com/bheisler/criterion.rs/pull/312) is here. PTAL.

Thank you :smile:

**Comment by bheisler** [comment]
I think this is done; the PR is merged. Closing for now, please re-open if there's anything further to do here.
