### ISSUE TITLE
How to measure more then one method

### ISSUE THREAD

**Issue by Tockra** [bheisler/criterion.rs#318]
Hey Guys,

I have a method `fn my_meth(val: u32); ` which runtime I want measure. 
So I want mesure the runtime of the different Inputs (vals) `vec![23,123,...,213]` and get the mean. 
How can I do it? At the moment I have this, but that outputs one measure per argument:
```rust
let id = &format!("{}::predecessor",T::TYPE)[..];
        c.bench(id,ParameterizedBenchmark::new(id,move
            |b: &mut Bencher, elem: &u32| {
                b.iter(|| data_structure.predecessor(*elem));
            },
            test_values.clone()
        ).sample_size(SAMPLE_SIZE));
```

Thank you ;)

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs!

Criterion.rs treats every parameter as defining a separate benchmark. If you want to combine multiple parameters into a single benchmark, you'll need to pass your list of parameters as a single unit. Something like this:

```
let id = &format!("{}::predecessor",T::TYPE)[..];
c.bench(id,ParameterizedBenchmark::new(id,move
    |b: &mut Bencher, elems: &Vec<u32>| {
        b.iter(|| {
            for elem in elems {
                data_structure.predecessor(*elem)
            }
        );
    },
    &[test_values.clone()]
).sample_size(SAMPLE_SIZE));
```

This will give you the total time to look up the predecessor of all of your elements. There isn't a built-in way to calculate the mean time over a variety of different inputs like this.

Honestly though, I would recommend leaving the benchmarks for each parameter separate. Seeing the different times for different parameters is useful information that would be lost if you averaged together the benchmarks for multiple parameters.

**Comment by Tockra** [comment]
Thank you for your response. There are small problems in your solution, but the following version does run:
```rust
        let id = &format!("{}::sucessor",T::TYPE)[..];
        c.bench(id,ParameterizedBenchmark::new(id,move
            |b: &mut Bencher, elems: &Vec<E>| {
                b.iter(|| {
                    for elem in elems {
                        data_strucuture.sucessor(*elem);
                    }
                });
            },
            vec![test_values]
        ).sample_size(SAMPLE_SIZE));
```

> Honestly though, I would recommend leaving the benchmarks for each parameter separate. Seeing the different times for different parameters is useful information that would be lost if you averaged together the benchmarks for multiple parameters.

The problem is, that I want to measure the runtime of a predecessor method of a data structure. So I could measure all relevant 2^32 possible values. So I reduce the measured runtimes to ~ 1000 random values. Then I will compare it with a binary search algorithm. 
If I would get 1000 different mean runtimes I wouldn't even know how to plot that output ;) ...
