### ISSUE TITLE
Improve Handling of Long Benchmarks

### ISSUE THREAD

**Issue by bheisler** [bheisler/criterion.rs#320]
After the release of 0.3.0, several folks commented that Criterion.rs' handling of long-running benchmarks is not great - it can take a very long time to measure these functions. That's true! It would be nice to improve on that. This is more of a tracking issue to describe the work required.

The biggest problem preventing this is an API one. I'd need to allow the user to specify whether they want each benchmark to use the slow- or fast-benchmark process, and (at the moment) I don't know what that should look like. Ultimately it would require a judgement call by the programmer and I'd prefer to try to avoid those where possible. One of the goals of Criterion.rs is to not require the benchmark author to understand statistics, but then how can they make an informed decision?

The analysis and measurement is relatively straightforward - since we can assume timing jitter is insignificant compared to the function itself, just run a smaller number of iterations and measure each one individually. That breaks all of the slope-based analysis so it would require new analysis code. Fortunately, the usual statistics (mean, std. dev., etc.) should all work more-or-less well, so that's probably OK, but it requires internal design changes and a bunch of work. It would probably also need different configuration settings than the fast-benchmark process.

**Comment by recmo** [comment]
I have an FFT benchmark that is parameterized over input size, ranging from several elements to several millions. The `n log n` execution time ranges from a few nanoseconds to tens of minutes.

Criterion is amazing for accurate numbers in the low end, but no matter what configuration parameters I provide, it seems to insist on running benches dozens of times, for benches taking many minutes, this takes hours to complete.

I would love for there to be a "run this bench exactly once" mode. I understand this does not give any statistical assurances, but for minute long functions this really doesn't matter much.

**Comment by rocurley** [comment]
Amusingly, I'm also running into this issue when trying to benchmark my FFT implementation. @Recmo did you wind up finding a workaround?

**Comment by bheisler** [comment]
Hey folks; I've been working on improving this a bit. In the next version, you'll be able to use a new sampling mode like so:

```
    let group = criterion.benchmark_group("sampling_mode");
    ...

    group.sampling_mode(SamplingMode::Flat);
    group.bench_function("Flat", |bencher| {
        bencher.iter(|| sleep(Duration::from_millis(10)))
    });
    ...
```

This will change how many iterations Criterion.rs performs in each sample, from a monotonically-increasing count to a flat count, resulting in a smaller minimum number of iterations. It still doesn't support one-shot benchmarking, but it should reduce execution times for long benchmarks significantly.

**Comment by rgreenblatt** [comment]
one-shot benchmarking would be very nice in general. One more use case which hasn't been mentioned is PGO.

Edit: actually, the best way to PGO is with --test

**Comment by bheisler** [comment]
For true one-shot benchmarking, I'd recommend https://github.com/bheisler/iai instead.

**Comment by mimoo** [comment]
sorry for bumping this one, but I was intrigued by that sentence: 

> Ultimately it would require a judgement call by the programmer and I'd prefer to try to avoid those where possible

I've run several time into this issue and I'm wondering why not do the following: for every bench (specifically call of `b.iter`), first run the thing **once**, then:

* if it took a **while** to run, then just stop there and use that metric. 
* If it was **fast**, then do normal bench.

**Comment by mimoo** [comment]
Also one question I have is why limit to 10 runs MINIMUM? Why not allow a single one? (I have some bench that take hours to run)

```rust
pub fn sample_size(&mut self, n: usize) -> &mut Self {
        assert!(n >= 10);
```

**Comment by adriangb** [comment]
> For true one-shot benchmarking, I'd recommend https://github.com/bheisler/iai instead.

For better or worse criterion has become a standard benchmark runner and has integrations in the ecosystem e.g. https://codspeed.io/docs/reference/codspeed-rust/criterion, using another framework is not always an option.

@bheisler could you help clarify if your opposition to a 1 shot benchmark is practical (would require a lot of refactor, etc.) or philosophical (e.g. if we removed the `assert!(n >= 10);` + handled not having samples for statistics would things mostly work)?
