### ISSUE TITLE
Gnuplot 2 different measured algorithms in one plot

### ISSUE THREAD

**Issue by Tockra** [bheisler/criterion.rs#325]
Hey,

I read the guide but I didn't find a solution for my problem. Maybe I overread something...

I want to measure 2 different Algorithms and compare their runtime like this:  
https://github.com/bingmann/sqlplot-tools/blob/master/examples/sorting-speed/speed.pdf

How can I achieve this ?

T

**Comment by Tockra** [comment]
The alternate would be to generate the graphs myself. That wouldn't be a problem if I have access to the single measures.

**Comment by bheisler** [comment]
Line plots like this are automatically generated into summary reports when appropriate. With Criterion.rs 0.3.0, all you need to do is use a `BenchmarkGroup` to group together the benchmarks on multiple different functions over multiple different inputs and this plot should be generated automatically in the report.

Incidentally, you do have access to the raw measures; they're stored in the `raw.csv` file that Criterion.rs also generates.
