### ISSUE TITLE
How does criterion compute his output?

### ISSUE THREAD

**Issue by Tockra** [bheisler/criterion.rs#331]
Hi,

ich tried to measure some functions. So I took the output of the target/criterion/GROUP/new/raw.cs file and compared it with the output of the console.
The raw.csv says:
```
group,function,value,throughput_num,throughput_type,sample_measured_value,unit,iteration_count
algo=STree<u40> method=predecessor size=64,,,,,5332271.0,ns,4
algo=STree<u40> method=predecessor size=64,,,,,10387811.0,ns,8
algo=STree<u40> method=predecessor size=64,,,,,10591259.0,ns,12
algo=STree<u40> method=predecessor size=64,,,,,13761446.0,ns,16
algo=STree<u40> method=predecessor size=64,,,,,18285185.0,ns,20
algo=STree<u40> method=predecessor size=64,,,,,16955577.0,ns,24
algo=STree<u40> method=predecessor size=64,,,,,20508028.0,ns,28
algo=STree<u40> method=predecessor size=64,,,,,20455766.0,ns,32
algo=STree<u40> method=predecessor size=64,,,,,23037282.0,ns,36
algo=STree<u40> method=predecessor size=64,,,,,25729753.0,ns,40
```
But the console says: 
```
Benchmarking algo=STree<u40> method=predecessor size=64
Benchmarking algo=STree<u40> method=predecessor size=64: Warming up for 3.0000 s
Benchmarking algo=STree<u40> method=predecessor size=64: Collecting 10 samples in estimated 5.1620 s (220 iterations)
Benchmarking algo=STree<u40> method=predecessor size=64: Analyzing
algo=STree<u40> method=predecessor size=64
                        time:   [660.92 us 699.95 us 792.89 us]
Found 2 outliers among 10 measurements (20.00%)
  2 (20.00%) high mild
slope  [660.92 us 792.89 us] R^2            [0.5065507 0.4017449]
mean   [726.18 us 1.0296 ms] std. dev.      [99.411 us 322.12 us]
median [643.24 us 1.0905 ms] med. abs. dev. [5.4267 us 380.80 us]
```

What are the right values? 

T

**Comment by bheisler** [comment]
As indicated by the name, the `raw.csv` file contains the raw measurements. The CLI and HTML output displays Criterion.rs' analysis of those measurements. Both are correct, as far as I know. The analysis process is documented in the [user guide](https://bheisler.github.io/criterion.rs/book/analysis.html).

**Comment by Tockra** [comment]
Okay, I think I should explain my problem:
You can see the 10 used measures above.
The median should be one of the two entrys:
```
algo=STree<u40> method=predecessor size=64,,,,,18285185.0,ns,20
algo=STree<u40> method=predecessor size=64,,,,,16955577.0,ns,24
```
That are 18,285ms or 16,956ms . 
Why does the output say something about median [643.24 us 1.0905 ms] ? That are so different values?
Did I chose the wrong raw.csv or is the median of the output (console) wrong?

**Comment by bheisler** [comment]
The raw.csv file (as documented in the [user guide](https://bheisler.github.io/criterion.rs/book/user_guide/csv_output.html)) contains the raw measurements. Criterion.rs runs the benchmark many times, but only measures the time once (or a few times) to reduce the effects of clock imprecision and the cost of getting the elapsed time. Thus, the raw measurements contain the number of iterations and the total time for that sample.

The statistics displayed by the CLI are based on the time per iteration, not the total time for the whole sample. To get the time per iteration, divide `sample_measured_value` by `iteration_count`.

**Comment by Tockra** [comment]
Okay. Do I understood you right and the following are the "real" runtimes? 
```
algo=STree<u40> method=predecessor size=64,,,,,20455766/32=639242.688,ns,32
algo=STree<u40> method=predecessor size=64,,,,,23037282/36=639924.5,ns,36
algo=STree<u40> method=predecessor size=64,,,,,25729753/40=643243.825,ns,40
algo=STree<u40> method=predecessor size=64,,,,,16955577/24=706482.375,ns,24
algo=STree<u40> method=predecessor size=64,,,,,20508028/28=732429.571,ns,28
algo=STree<u40> method=predecessor size=64,,,,,13761446/16=860090.375,ns,16
algo=STree<u40> method=predecessor size=64,,,,,10591259/12=882604.917,ns,12
algo=STree<u40> method=predecessor size=64,,,,,18285185/20=914259.25,ns,20
algo=STree<u40> method=predecessor size=64,,,,,10387811/8=1298476.375,ns,8
algo=STree<u40> method=predecessor size=64,,,,,5332271/4=1333067.75,ns,4
```

So the median is 732429.571ns = 732.430us  and 860090.375ns= 860.09us ?
But from where comes the interval [643.24 us 1.0905 ms] ?

**Comment by bheisler** [comment]
This is also in the [user guide](https://bheisler.github.io/criterion.rs/book/analysis.html). Criterion.rs takes a large number (by default, 100,000) bootstrap samples and calculates various statistics (such as the median) on those samples. That creates a distribution, which can be used to compute a confidence interval around the sample median.

**Comment by Tockra** [comment]
I am asking, because I want to plot the measured values (without gnuplot functions) and the only way to find the median I see is to use the new/raw.csv file and compute it on my own. So it is very important not to calculate the wrong value.
This is the reason I'm asking.

**Comment by bheisler** [comment]
Ah, I see. In that case, yes; you've understood correctly. The statistics (median, confidence intervals, etc.) are not saved to disk and are not available through Criterion.rs' API, so you would have to compute them yourself.

Out of curiosity, what are you planning to do with these values?
