### ISSUE TITLE
Would it be possible to get benchmark_with_input to take a mutable reference as the parameter?

### ISSUE THREAD

**Issue by arthmis** [bheisler/criterion.rs#333]
I'm essentially trying to do:
```rust
pub fn sobel_x_y(c: &mut Criterion) {
    let mut group = c.benchmark_group("Sobel Edge Detector");
    group.confidence_level(0.01);
    group.sample_size(50);

    let mut image = image::open("../images/some_image.jpg")
        .expect("image not found")
        .to_luma();

    group.bench_with_input("Sobel full", image, move |b, mut image| {
        b.iter(|| sobel_mut(&mut image)));
    });

    group.finish();
}
```
I want the `bench_with_input` function to take ownership of image so I can pass a mutable reference when benching the sobel function. Is that possible?

The error I get asks to pass a reference of image, but if I do that then it says it can't borrow as mutable when I call `sobel_mut`.

**Comment by arthmis** [comment]
realized i can just take ownership this way. 
```rust
group.bench_function("Sobel full", move |b| {
    b.iter(|| sobel_mut(&mut image));
})
```

Still would like to know if the above question would be possible.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs.

I'm not sure I understand why `bench_with_input` would need to take ownership of the image and convert it to a reference. I don't have much time right now so I haven't tried this, but it seems like you could pass the image as a mutable reference:

```
group.bench_with_input("Sobel full", &mut image, move |b, image_ref| {
    b.iter(|| sobel_mut(image_ref)));
});
```

**Comment by arthmis** [comment]
If I try the above example it gives the error:

```rust
error[E0308]: mismatched types
  --> benches/sobel.rs:31:29
   |
31 |         b.iter(|| sobel_mut((image_ref)));
   |                             ^^^^^^^^^^^ types differ in mutability
   |
   = note: expected type `&mut image::buffer::ImageBuffer<image::color::Luma<u8>, std::vec::Vec<u8>>`
              found type `&image::buffer::ImageBuffer<image::color::Luma<u8>, std::vec::Vec<u8>>`
```

Frankly what I decided to use instead works perfectly fine. It was just interesting that I can't pass a mutable reference to `bench_with_input`.

You can close this issue if you want. It was probably unnecessary.  Thank you for answering.
