### ISSUE TITLE
Can I change the measurement configuration in different benches?

### ISSUE THREAD

**Issue by Fullstop000** [bheisler/criterion.rs#339]
Some benches with large input could be slowly and criterion.rs gives me some warning
```
Unable to complete 100 samples in 1.0s. You may wish to increase target time to 3.0s or reduce sample count to 40
```
But I don't want to change the global configuration so that total measurement time stays short.

So is there any way that I can configure measurement in each bench like `set_measurement_time()`?

**Comment by Fullstop000** [comment]
I found that there is a struct called `Benchmark` and it's wrapped by macro `benchmark_config!`. And it is exactly what I want.

But why is `Benchmark` and `ParameterizedBenchmark` decorated by `#[doc(hidden)]`?

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs.

`Benchmark` and `ParameterizedBenchmark` are deprecated and shouldn't be used in new code. The `BenchmarkGroup` struct also allows you to configure settings on individual benchmarks, and is the recommended replacement for the other two structs.

**Comment by Fullstop000** [comment]
@bheisler Thank you for help! `BenchmarkGroup` works perfectly for me now.
