### ISSUE TITLE
Mention of removed ParameterizedBenchmark in current docs

### ISSUE THREAD

**Issue by gz** [bheisler/criterion.rs#340]
https://github.com/bheisler/criterion.rs/blob/master/book/src/user_guide/comparing_functions.md
mentions ParameterizedBenchmark which can no longer be found in the API docs (but is still pub)

**Comment by bheisler** [comment]
Ah, I missed that one. Thanks! I probably won't get around to fixing this right away, but I'll fix it in time for the next release.

**Comment by ronvoluted** [comment]
Oh I was going off those docs. Does this mean that `black_box` is no longer automatically applied?

**Comment by bheisler** [comment]
Yes, `black_box` is still applied automatically to inputs that you pass through the `BenchmarkGroup::bench_with_input` function, as well as any output returned from the benchmark. If you have inputs you're not passing through `bench_with_input` or outputs that you're not returning, you will have to handle those yourself.
