### ISSUE TITLE
Is it possible to include benchmarks in the same file as the functions/module being benchmarked?

### ISSUE THREAD

**Issue by josephrocca** [bheisler/criterion.rs#341]
Hi! [This page](https://doc.rust-lang.org/unstable-book/library-features/test.html) has an example of the built-in (but unstable) benchmarker being used within the same file as the code that is being benchmarked:

```rust
#![feature(test)]

extern crate test;

pub fn add_two(a: i32) -> i32 {
    a + 2
}

#[cfg(test)]
mod tests {
    use super::*;
    use test::Bencher;

    #[test]
    fn it_works() {
        assert_eq!(4, add_two(2));
    }

    #[bench]
    fn bench_add_two(b: &mut Bencher) {
        b.iter(|| add_two(2));
    }
}
```
Is this sort of thing possible using criterion?

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs.

No, this is not currently possible.

**Comment by josephrocca** [comment]
No worries - thanks for your work on this lib in any case!
