### ISSUE TITLE
Specifying iteration count per sample

### ISSUE THREAD

**Issue by kstrafe** [bheisler/criterion.rs#342]
It would be useful to be able to specify the maximum amount of iterations for each sample. My use-case is I have a system that pushes some data to a fixed-size queue and would like to stop the sample if the queue is full.

**Comment by bheisler** [comment]
Hey, thanks for the suggestion and thanks for your patience.

Unfortunately, this is not possible. The iteration counts are chosen automatically to enable certain statistical analyses later on.

As a workaround, you could set the benchmark time for this benchmark to a very small duration. That should cause Criterion.rs to pick the minimum possible iteration count. From there, you can control the maximum number of iterations in a sample by changing the number of samples.

Sorry I can't be of more help.

**Comment by bluenote10** [comment]
How does setting something per benchmark function work at all? `criterion_group!` requires to pass `&mut Criterion`, but the setters like `sample_size` require `mut Criterion` so the following won't work:

```rust
fn benchmarks(c: &mut Criterion) {
    c.sample_size(size1).bench_function("bench1", |b| b.iter(...));
    c.sample_size(size2).bench_function("bench2", |b| b.iter(...));
}

criterion_group! {
    name = benches;
    config = Criterion::default();
    targets = benchmarks
}
criterion_main!(benches);
```

Is there a way to make that work? I'm new to Rust, so maybe I'm missing something.

**Comment by bheisler** [comment]
You can also use benchmark groups to adjust the sample count for a single benchmark.
