### ISSUE TITLE
`[[bench]] required-features = [...]` doesn't seem to work?

### ISSUE THREAD

**Issue by isislovecruft** [bheisler/criterion.rs#344]
Hi!

I'm trying to use cargo's `required-features` field in my `Cargo.toml` with in the `[[bench]]` section where I override the harness, like so:

```toml
[[bench]]
name = "ed25519_benchmarks"
harness = false
required-features = ["batch"]
```

However, when I do this and run `cargo bench`, none of the criterion benches in the `bench/` directory are run, nor any of the tests in the `tests/` directory, but only the single internal/private unit test my library contains, which is ignored since we're in bench mode:

```
    Finished release [optimized] target(s) in 4.99s
     Running target/release/deps/ed25519_dalek-2a1a5b83c1c466d3

running 1 test
test ed25519::test::keypair_clear_on_drop ... ignored

test result: ok. 0 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out
```

Is this something specific to overriding the default harness with criterion? Or possibly it's a bug in cargo? (If the latter, sorry, I'll transfer this bug to them.)

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs!

I wasn't familiar with this feature ([here's the link](https://doc.rust-lang.org/cargo/reference/manifest.html#the-required-features-field-optional) for the docs). What the required-features field means is that that benchmark will only be compiled if a particular feature is enabled. I found this surprising - I had initially assumed it would enable that feature for that benchmark.

You didn't specify how you're running your benchmarks, so it's possible that you made the same mistake I did - you would need to run `cargo bench --features batch`, or this benchmark wouldn't be compiled.

If that is what you're running, then I'm stumped. Criterion.rs' harness isn't doing anything very clever, it just uses some macros to generate a basic `main` and some extra functions. In this case, I think you'd have to talk to the Cargo team.
