### ISSUE TITLE
Benchmarks won't run when invoked directly, even with --profile-time

### ISSUE THREAD

**Issue by joshhansen** [bheisler/criterion.rs#345]
I'm attempting to profile some benchmarks according to the directions in the guide. In my code, when I run `cargo bench` it says that it runs a file called `target/release/deps/nearest_adjacent_unobserved-80a45e4794ee3333`. If I understand correctly, this is the executable I would profile, e.g. with cachegrind. But when I run it, I can't get it to actually run the benchmarks. I've tried using various command line flags, --profile-time, --warm-up-time, --sample-size, and none of them appear to make a difference. Instead of the benchmarks running, it simply prints "Success".

This same behavior can be seen on the fibonacci example in the Getting Started guide. The output of target/release/deps/fibonacci-4471309597993ac6 is inavariably:

```
Testing fib 20
Success
```
What am I missing?
criterion 0.3.0

**Comment by bheisler** [comment]
Hey, thanks for the question.

When `cargo` runs benchmarks, it passes along a `--bench` argument to the benchmark executables. Criterion.rs looks for that argument (as well as the `--test` argument) and tries to do the thing that makes sense for how the user would have invoked `cargo`. Unfortunately, that means that if you run the executables directly (without going through `cargo`) they can be a bit strange - you'll need to add the `--bench` argument to the command line to actually perform the benchmarks.

I've added a couple of notes to the user guide explaining this.
