### ISSUE TITLE
Malformed violin plot when comparing functions

### ISSUE THREAD

**Issue by mexus** [bheisler/criterion.rs#348]
Hello there,

After upgrading to criterion-0.3 I've found that comparison report doesn't work as expected anymore :( On ["fibonacci" comparison](https://bheisler.github.io/criterion.rs/book/user_guide/comparing_functions.html) I'm getting the following result:

![image](https://user-images.githubusercontent.com/3609357/66667852-a459b680-ec5c-11e9-8558-b6c977ab25a7.png)

And that's what I get when running gnuplot on generated `violin.gnuplot` manually:
![image](https://user-images.githubusercontent.com/3609357/66668127-26e27600-ec5d-11e9-97e6-33bd73aedcd7.png)

That's totally weird and I'm a little bit lost. Might it be that I've got an "incomatible" gnuplot version or something? It's 5.3 on my machine (also tested with 5.2.7 with the same results).

Thanks!

**Comment by gz** [comment]
This also happens for me.

**Comment by TyberiusPrime** [comment]
I observe the same with gnuplot 5.2, patchlevel2 (ie. what's in the ubuntu 18.04 repositories)

(After some digging in the gnuplot file I think it's the actual data being dumped)

**Comment by TyberiusPrime** [comment]
Since I need a usable comparison plot today, maybe this is useful to the other's affected.
```python
import pandas as pd
import dppd
import dppd_plotnine
from +athlib import Path

dp, X = dppd.dppd()


def load_new():
    input_files = list(Path("target/criterion/").glob("**/raw.csv"))
    input_files = [x for x in input_files if "/new/" in str(x)]
    dfs = []
    for i in input_files:
        print(i)
        df = pd.read_csv(i, sep=",")
        dfs.append(df)
    return pd.concat(dfs)


df = load_new()

for value, sub_df in df.groupby("value"):
    filename = "target/criterion/function_violin_%s.svg" % value
    print(filename)
    #insert dummy 0 iterations, 0 nanosecond entry so diff doesn't eat the first sample
    sub_df = sub_df[["group", "function", "sample_measured_value", "iteration_count"]]
    sub_df = pd.concat(
        [
            pd.DataFrame(
                {
                    "group": [sub_df['group'].iloc[0]],
                    "function": [sub_df['function'].iloc[0]],
                    "sample_measured_value": [0],
                    "iteration_count": [0],
                }
            ),
            sub_df,
        ]
    )

    (
        dp(sub_df)
        .assign(
            nsec_delta=X.sample_measured_value.diff(),
            iter_count_delta=X.iteration_count.diff(),
        )
        .iloc[1:]
        .assign(msec=X.nsec_delta / X.iter_count_delta / 1e6)
        .p9()
        .add_jitter("function", "msec", color="function")
        .add_boxplot("function", y="msec", color="function", _alpha=0.5)
        .coord_flip()
        .facet_wrap("group",ncol=1)
        .render(filename)
    ).pd
```

Looks like this:
![image](https://user-images.githubusercontent.com/1257580/67866592-7a900300-fb29-11e9-9b44-c4984b45e30b.png)

(fixed a data interpretation issue from my earlier draft)

**Comment by TyberiusPrime** [comment]
You might ask about the below 0 values... the answer is I don't know... I observe rows like this in the raw.csv:
```
18  No_seek  stream_count   1000             NaN              NaN            211670320.0   ns              171
19  No_seek  stream_count   1000             NaN              NaN            294563310.0   ns              180
20  No_seek  stream_count   1000             NaN              NaN            241839477.0   ns              189
```
Note how the iterations 180-188 appear to use a negative amout of time?

**Comment by drdozer** [comment]
I'm also seeing blank violin plots. Are the gnuplot scripts saved somewhere so that I can double-check what it is generating?

**Comment by gz** [comment]
AFAIK yes, they should be somewhere under the target/ directory.

**Comment by drdozer** [comment]
So some of my violin plots work, and others don't. The plots that don't appear to have polys for the violin that are very narrow (e.g. 0.09, according to the chrome devtools) and a nonsense hit-box location. The violin polys that are rendering have a sane range for their widths.

**Comment by Timmmm** [comment]
To get the Gnuplot scripts, run the benchmark with the `CRITERION_DEBUG` environment variable set.

Unfortunately the scripts save all their numbers in binary format, which is nice and efficient but not very helpful for debugging! However, looking at the data, I too seem to have sample times that go backwards, yet it gives a sensible looking graph for the individual PDF:

![image](https://user-images.githubusercontent.com/376842/69745189-a8249800-1139-11ea-92d1-692ea326db50.png)

This is making me doubt the actual results of Criterion!

**Comment by Timmmm** [comment]
Actually, I read [the documentation for the CSV](https://bheisler.github.io/criterion.rs/book/user_guide/csv_output.html) and it is not how I or @TyberiousPrime assumed - basically @TyberiusPrime you've analysed the output completely wrong, which is why there are negative values.

**Comment by schell** [comment]
My violin plots are sometimes missing, which seems similar to this. I think this happens when the data point doesn't "fit" within the range the plotting lib chose, or if the width is too small. Is there a way to limit the violin width to 1 pixel so we can see where it lies?
