### ISSUE TITLE
How to benchmark a function from my crate

### ISSUE THREAD

**Issue by lucidBrot** [bheisler/criterion.rs#353]
I got the [fibonacci example](https://bheisler.github.io/criterion.rs/book/getting_started.html) to work with the function within `my_benchmark.rs`. But I cannot figure out how I can benchmark a function that I defined in my own crate.

My folder structure is like this:
```
mycratename
| - benches
    | - my_benchmark.rs
| - src
    | - main.rs
| - target
| - Cargo.toml
| - Cargo.lock
```

How could I benchmark a function that is defined in `main.rs`?  
Or is that already documented somewhere? In that case, I think a more obvious link is needed

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs!

Unfortunately, it's not currently possible to use Criterion.rs with binary crates, only with library crates (see [this issue](https://github.com/rust-lang/cargo/issues/4316) for more details). If you have a library crate, you can take a look at the [Getting Started](https://bheisler.github.io/criterion.rs/book/getting_started.html) page of the user guide, which shows an example of benchmarking a function from the `lib.rs` file.

Edit: I almost forgot; this is documented in the [Known Limitations](https://bheisler.github.io/criterion.rs/book/user_guide/known_limitations.html) section of the user guide.

Edit2: It's fairly common for binary crates in Rust to contain only a thin layer of glue code (parsing command-line arguments, etc.) around a library crate that implements the application logic. I don't actually remember just off-hand why that's done, but it does handily solve this problem.

**Comment by lucidBrot** [comment]
Thanks for that reply! I'll have to read up on the difference between creating a lib vs binary crate (I'm kinda new to rust), but it does sound like I should be able do do what your Edit2 suggests

**Comment by lucidBrot** [comment]
Okay. Turns out I would have needed to use a library instead of a binary crate anyways, because I want to use my crate in a different crate and it is not possible to use binary crates in other crates. So thank you for the suggestion!

I don't see the point of binary crates then... because libraries can have executables with `cargo run --example`.

For anybody else with the same problem though: All it takes is renaming `main.rs` to `lib.rs`
