### ISSUE TITLE
report doesn't seem to be generated

### ISSUE THREAD

**Issue by drdozer** [bheisler/criterion.rs#354]
I have a cargo workspace project with a child project that contains benchmarks. When I run `cargo +nightly bench` it performs the benchmarking and generates an `index.html` file and various json and csv files. However, there are no plots or tables or links in the `index.html` report, and no other files in that report directory.

I have gnuplot installed, and can run it from the command-line. I've copy-pasted the fib benchmarks and most of their cargo.

```
<body>
   <div class="body">
   <h2>Criterion.rs Benchmark Index</h2>
   See individual benchmark pages below for more details.
   <ul>
   <li>Fibonacci-Custom</li>
   <li>Fibonacci-Custom-copy</li>
   <li>Fibonacci-Simple</li>
   <li>Fibonacci-Simple-copy</li>
   </ul>
   </div>
   <div id="footer">
   <p>This report was generated by
   <a href="https://github.com/bheisler/criterion.rs">Criterion.rs</a>, a statistics-driven benchmarking
   library in Rust.</p>
   </div>
</body>
```

**Comment by drdozer** [comment]
I'm now baffled. If I run the benchmark within criterion.rs/macro, it generates the output as expected. If I copy that project into mine and tidy up the cargo and stub out lib.rs, it fails to generate the charts. The only difference that I can guess at is that the macro project is building against the git main code for criterion within the project, and against the cargo release in mine.

**Comment by drdozer** [comment]
So I have a work-around.

If I use 

```
[dev-dependencies]
criterion = "^0.3"
criterion-macro = "^0.3"
```

it fails to generate reports. If instead I use

```
[dev-dependencies]
criterion = { git = "https://github.com/bheisler/criterion.rs.git" }
criterion-macro = { git = "https://github.com/bheisler/criterion.rs.git" }
```

the reports are generated. So it must be some bug that is symptomatic on my system for the 0.3.0 release but is fixed in master.

**Comment by geoffreywiseman** [comment]
This is true for me as well, even without `criterion-macro`. If I depend on GitHub, I get the report, if I depend on 0.3, I get no report.

**Comment by bheisler** [comment]
My apologies, I completely missed this. It's good that it seems to be fixed using the latest git version. I intend to publish a new version soon-ish so hopefully that will work for you.
