### ISSUE TITLE
Allow comparative analysis of two baselines

### ISSUE THREAD

**Issue by 197g** [bheisler/criterion.rs#357]
## Motivation

Criterion's elaborate statistical analysis can only be run on a *current, newly performed* benchmark against some previously established baseline measurement. It would also be useful to be able to do a comparison without having to do a new expensive benchmark run and instead utilize two saved measurements/baselines.

## Use cases

Two main use cases come to mind:

1. Compare one state of a program against multiple other previous runs such as against the integration branch, against master, and against the last release. But this may also apply to experimentation where several competing ideas should be compared against each other instead of the linear fashion that `baseline` suggests.

2. Allow the analysis to occur on a separate (virtual) machine than the performance measurement. For example, when running the performance capture in a separate machine to ensure the better control of the hardware and the runtime environment. But the output is persisted into the `target` directory which is typically wiped in CI, and the comparison analysis is not saved at all. A current workaround is to capture a the full analysis run but this restricts it to comparing the exact chosen baseline against that CI run.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs and thanks for the suggestion!

It's a good idea, but difficult to implement for internal code-structure reasons. One of the things I'd like to do at some point is separate the measurement code from the analysis & report-generation code and move the latter into a separate CLI or cargo plugin (eg `cargo criterion`). That would make it easy to implement this.

Unfortunately, I haven't had a lot of time to work on Criterion.rs lately, so I can't make any promises.
