### ISSUE TITLE
Explore dropping `rand` for `oorandom` or something similar

### ISSUE THREAD

**Issue by bheisler** [bheisler/criterion.rs#361]
The rand crate has been kind of a hassle with breakages and complex dependency trees and whatnot. Since Criterion.rs only uses it for selection-with-replacement (and even implements most of the code for _that_ internally) the rand crate is mostly superfluous.

Another valid option would be to just write up a little xoroshiro generator or PCG or something and embed that directly into Criterion.rs' code.

**Comment by icefoxen** [comment]
So THIS is why `oorandom` has gotten about 8000 downloads in the last three days.

*insert lots of panicked screaming here*

...Okay, now that that's out of my system, hope it works out well for you!  Let me know if there's any problems.

**Comment by bheisler** [comment]
Haha, sorry, I suppose I could have mentioned something. As I said in the issue description, I have very limited needs from an RNG so I don't expect any trouble from oorandom. Thanks for publishing the exact crate that I needed!

**Comment by icefoxen** [comment]
Hah, no worries, just was startling. I thought crates.io was broken! Glad it does what you need though.
