### ISSUE TITLE
Consistent scales

### ISSUE THREAD

**Issue by segeljakt** [bheisler/criterion.rs#371]
Would it be possible to add a setting for forcing consistent scales across benchmarks in a benchmark group?

Currently, it looks like this:

![example](https://cdn.discordapp.com/attachments/274215136414400513/667883794035900437/unknown.png)

**Comment by gakonst** [comment]
I agree that this would be a great feature to have, it's very hard to compare otherwise.

**Comment by segeljakt** [comment]
Also, would be nice if each axis starts at 0:
![image](https://user-images.githubusercontent.com/15143039/75092407-79229480-5577-11ea-878b-8b5518212322.png)

**Comment by bheisler** [comment]
Hey, thanks for the suggestion and thanks for trying Criterion.rs.

Right now consistent scaling would be difficult to implement in a clean way, but I definitely agree that it would be good to make it more easy to compare Criterion.rs' reports.

**Comment by bheisler** [comment]
I'm going to close this for now as a duplicate of #367, but thanks again for the suggestion.
