### ISSUE TITLE
Unexpected segfault on basic benchmark code

### ISSUE THREAD

**Issue by jmcph4** [bheisler/criterion.rs#374]
# Environment #
OS: Windows 7 (64-bit)
`rustc`: rustc 1.40.0 (73528e339 2019-12-16)
`cargo`: cargo 1.40.0 (bc8e4c8be 2019-11-22)
`rustup`: rustup 1.21.1 (7832b2ebe 2019-12-20)
Toolchain: stable-x86_64-pc-windows-msvc

# Background #
I was attempting to add a benchmark for appending elements to an array-backed list type for my collections library called [Oxcart](https://github.com/jmcph4/oxcart). To do this, I followed [the instructions in the documentation](https://bheisler.github.io/criterion.rs/book/getting_started.html).

The benchmark code is located at `benches/arraylist_append.rs`:

```rust
use criterion::{black_box, criterion_group, criterion_main, Criterion};
use oxcart::list::List;
use oxcart::arraylist::ArrayList;

fn criterion_benchmark(c: &mut Criterion) {
    let mut list: ArrayList<u64> = ArrayList::new();
    c.bench_function("arraylist.append 20",
                     |b| b.iter(|| list.append(black_box(20))));
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```

To see the code for relevant `ArrayList` types, see the source [here](https://github.com/jmcph4/oxcart/blob/master/src/arraylist.rs).

# Actual Behaviour #
    $ cargo bench
       Compiling oxcart v0.1.0 (E:\Dev\oxcart)
        Finished bench [optimized] target(s) in 2.92s
         Running target\release\deps\oxcart-5c0943de998eba7f.exe
    
    running 15 tests
    test arraylist::test::test_get_error_out_of_bounds ... ignored
    test arraylist::test::test_get_mut_error_out_of_bounds ... ignored
    test arraylist::test::test_get_mut_normal_head ... ignored
    test arraylist::test::test_get_mut_normal_middle ... ignored
    test arraylist::test::test_get_mut_normal_tail ... ignored
    test arraylist::test::test_get_normal_head ... ignored
    test arraylist::test::test_get_normal_middle ... ignored
    test arraylist::test::test_get_normal_tail ... ignored
    test arraylist::test::test_insert_error_out_of_bounds ... ignored
    test arraylist::test::test_insert_normal_middle ... ignored
    test arraylist::test::test_new_normal ... ignored
    test arraylist::test::test_remove_error_out_of_bounds ... ignored
    test arraylist::test::test_remove_normal_head ... ignored
    test arraylist::test::test_remove_normal_middle ... ignored
    test arraylist::test::test_remove_normal_tail ... ignored
    
    test result: ok. 0 passed; 0 failed; 15 ignored; 0 measured; 0 filtered out
    
         Running target\release\deps\arraylist_append-9510dfaef3362d67.exe
    Gnuplot not found, using plotters backend
    Benchmarking arraylist.append 20: Warming up for 3.0000 smemory allocation of 2147483648 bytes failederror: bench failed
    Segmentation fault

# Expected Behaviour #
No segmentation faults and output similar to that described in the aforementioned documentation.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs!

It looks like you're adding an unbounded number of elements to a single ArrayList. Based on the error message, it looks like the ArrayList is trying to grow to >2GB in size and failing to allocate memory, so I don't think this is a problem with Criterion.rs.

I would recommend [`iter_batched`](https://bheisler.github.io/criterion.rs/criterion/struct.Bencher.html#method.iter_batched) instead of `iter` - that will allow you to create a new ArrayList for every iteration of the benchmark and then insert a single element into it. For example:

```rust
fn criterion_benchmark(c: &mut Criterion) {
    c.bench_function("arraylist.append 20",
                     |b| b.iter_batched(
                         || ArrayList::new::<u64>(),
                         || {
                             list.append(black_box(20);
                             list // Return list to avoid measuring drop
                         }),
                         BatchSize::SmallInput,
                     ));
}
```
