### ISSUE TITLE
Unexpected overhead from `black_box`

### ISSUE THREAD

**Issue by bluenote10** [bheisler/criterion.rs#375]
First of all, thanks for putting all the effort into this project!

I'm trying to determine the benchmark overhead on my machine, and I'm not fully sure what is the proper way to do it. Basically I'm getting two quite different values for "doing nothing" depending on whether `black_box` is involved or not:

```rust
use criterion::{black_box, criterion_group, criterion_main, Criterion};

fn basic_test(c: &mut Criterion) {
    c.bench_function("noop (const)", |b| b.iter(|| 1.0));
    c.bench_function("noop (const w/ black_box)", |b| b.iter(|| black_box(1.0)));
}

criterion_group!(benches, basic_test);
criterion_main!(benches);
```

```
noop (const)            time:   [263.29 ps 263.31 ps 263.33 ps]                         
                        change: [-0.1358% -0.0868% -0.0479%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 12 outliers among 100 measurements (12.00%)
  1 (1.00%) low mild
  6 (6.00%) high mild
  5 (5.00%) high severe

noop (const w/ black_box)                                                                             
                        time:   [531.89 ps 532.28 ps 532.68 ps]
                        change: [-0.2040% -0.0298% +0.1564%] (p = 0.75 > 0.05)
                        No change in performance detected.
Found 8 outliers among 100 measurements (8.00%)
  1 (1.00%) low mild
  3 (3.00%) high mild
  4 (4.00%) high severe
```
Basically the time doubles depending on whether `black_box` is used. In terms of the timing model I would have expected that I'm measuring `mem::drop(O) + Range::next`. Why is this affected by `black_box`, and which of the two values is the correct estimate of the overhead?

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs!

When you see benchmark numbers in picoseconds that generally means you're looking at individual instructions, so the only way to be sure is to look at the assembly. Sadly, Criterion.rs is not available on the Rust playground and I only have so much time before I leave for work, so I'll have to leave that up to you.

Criterion.rs' fake `black_box` function performs an atomic read of the input, which is unlikely to be optimized away. In this case, I would guess that's probably what you're seeing - one extra instruction inserted that does an atomic read and discards the value. You could maybe try using a nightly compiler and enabling the `real_blackbox` feature in Cargo - that will use the (unstable) compiler-intrinsic black box instead, which may have less overhead.

In either case, the overhead should be negligible for benchmarks at the nanosecond level and above.

**Comment by bluenote10** [comment]
Thanks for the clarification! It looks like in most cases each `black_box` adds one cycle to the loop, which can blur results slightly:

```rust
fn add_three(a: i64, b: i64, c: i64) -> i64 {
    a + b + c
}

c.bench_function("add_three (single black_box)", |b| b.iter(
    || add_three(black_box(1), 1, 1)
));
c.bench_function("add_three (three black_boxes)", |b| b.iter(
    || add_three(black_box(1), black_box(1), black_box(1))
));
c.bench_function("cos (single black_box)", |b| b.iter(
    || (black_box(1.0_f64)).cos()
));
c.bench_function("cos (three black_boxes)", |b| b.iter(
    || (black_box(black_box(black_box(1.0_f64)))).cos()
));
```

```
add_three (single black_box)                                                                             
                        time:   [526.74 ps 526.84 ps 526.94 ps]

add_three (three black_boxes)                                                                             
                        time:   [1.0600 ns 1.0606 ns 1.0612 ns]

cos (single black_box)  time:   [12.157 ns 12.159 ns 12.162 ns]                                    

cos (three black_boxes) time:   [13.889 ns 13.892 ns 13.895 ns]                                     
```

I was mainly confused because some parts of the docs sounded like it has zero overhead. But if this gets solved by the real blackbox in the long term, there is probably no need to refine the docs.

Overall, using the subtractive model discussed in #376 works quite well for me as a work-around, because I can match the black_boxes in the noop function, producing pretty precise results also in the low nanosecond range.
