### ISSUE TITLE
Support for PGO benchmarks

### ISSUE THREAD

**Issue by zbraniecki** [bheisler/criterion.rs#379]
Rust now supports PGO and it seems to provide some performance benefits in my limited experience - https://doc.rust-lang.org/rustc/profile-guided-optimization.html

Would be nice to have a way to instrument criterion's `cargo bench` to run against PGO or even compare PGO and non-PGO.

**Comment by bheisler** [comment]
Hey, thanks for the suggestion and thanks for trying Criterion.rs.

Unfortunately, this is not possible to implement in Criterion.rs itself. I would recommend using a shell script or something of that nature.
