### ISSUE TITLE
Alternative / Configurable Output Directory?

### ISSUE THREAD

**Issue by JP-Ellis** [bheisler/criterion.rs#381]
Is it possible to have Criterion produce its output in a specified directory?

I'm asking this because I have my `CARGO_TARGET_DIR` environment variable set to be shared (that is: `~/.cache/cargo`) and unfortunately, this means that the Criterion results from all crates are combined there (and override each other).  It also makes it a bit more difficult to retrieve the results.

Furthermore, an additional benefit of having a separate directory means that `cargo clean` won't remove historical results.

**Comment by bheisler** [comment]
Hey, thanks for the suggestion and thanks for trying Criterion.rs.

This is not currently possible, no.

**Comment by JP-Ellis** [comment]
Any plans to support this in the future perhaps?  I guess it wouldn't be difficult to add a section to `Cargo.toml` for this (provided the format allows for additional section, which I believe it does).

**Comment by bheisler** [comment]
I suppose it could be added. I haven't had a ton of time to work on this lately, I'm afraid.

**Comment by faern** [comment]
I second this. I have `CARGO_TARGET_DIR` set on my Rust dev machines and it makes the criterion results very mixed up from different crates.

An alternative to letting crates specify where their Criterion results go, could it not default to write them in `$CARGO_TARGET_DIR/criterion/{crate name}/{bench name}/` instead of just `$CARGO_TARGET_DIR/criterion/{bench name}/`?

**Comment by JP-Ellis** [comment]
I agree with having `$CARGO_TARGET_DIR/criterion/{crate name}/{bench name}/` as a preferred default option (and obviously the first preference being for specified output directory when that's specified).

**Comment by bheisler** [comment]
Sorry for not mentioning this sooner; the next version of Criterion.rs will support a `CRITERION_HOME=/path/to/criterion/dir` environment variable. I'm also working on a `cargo criterion` subcommand, which compiles and runs benchmarks like `cargo bench` - that will allow overriding the output directory with command-line argument, environment variable or configuration file.
