### ISSUE TITLE
Command line arguments are ignored

### ISSUE THREAD

**Issue by arazabishov** [bheisler/criterion.rs#386]
Executing a command: 

```
cargo bench -- --sample-size=10 # or
cargo bench -- --sample-size 10
```

throws an error:
```
error: Unrecognized option: 'sample-size'
error: bench failed
```
At the beginning I thought that I am not getting syntax right, but it seems to be a bug after all. Please, let me know if you won't be able to reproduce the issue.

**Comment by pksunkara** [comment]
https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options

**Comment by arazabishov** [comment]
Thanks @pksunkara!
