### ISSUE TITLE
unable to plot using GNUplot

### ISSUE THREAD

**Issue by JAicewizard** [bheisler/criterion.rs#388]
when I run cargo bench I get the following error:`Criterion.rs ERROR: Error in Gnuplot: line 0: Can't plot with an empty x range!`

I just installed GNUplot and updated criterion.
I am not sure what other information to give.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.

Well, if you can share your source code, that would help. Does it work if you use the plotters backend instead? You could also try [enabling debug mode](https://bheisler.github.io/criterion.rs/book/index.html#debug-output) and sharing the GNUPlot scripts that it generates.

**Comment by JAicewizard** [comment]
sample source code:
```
#[macro_use]
extern crate criterion;
use criterion::black_box;
use criterion::Criterion;

criterion_main!(test);
criterion_group! {
	name = test;
	config = Criterion::default().confidence_level(0.01).measurement_time(std::time::Duration::new(1, 0));
	targets = bench_test,
}
fn bench_test(c: &mut Criterion) {
	c.bench_function("test", |b| {
		let i = 5;
		b.iter(|| {
			black_box(i + 5);
		})
	});
}
```

[slope.gnuplot.txt](https://github.com/bheisler/criterion.rs/files/4301950/slope.gnuplot.txt)
This does have a corresponding svg with data in it in the same folder. (.txt added for github to be happy)

I couldnt get `cargo bench --plotting-backend plotters test` to work, so I uninstalled gnuplot. The plotters backend panics at ```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/jaap/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.1/src/plot/plotters_backend/distributions.rs:30:15```

**Comment by bheisler** [comment]
Interesting! I hadn't thought about this before, but if you set your confidence level to be super small like that, then things break. I'll probably have to put a minimum bound on the confidence level in the next breaking change release.

In the meantime, could you tell me why you're setting the confidence level so small? That means the confidence interval will be so tight that the true value lies within the interval just 1% of the time, so it doesn't seem very useful. Perhaps you meant to use 0.99?

**Comment by bheisler** [comment]
Now that I look at it, I can see the documentation isn't very clear on just what the confidence level means, so I'll update the documentation.

**Comment by JAicewizard** [comment]
yeah I didn't know what to set it to, I only really cared about the time numbers.
I thought "well my benchmarks vary so much, I guess I have little confidence in the numbers" so I set it super low, I couldn't really see a difference.

**Comment by bheisler** [comment]
The documentation was updated already, I just forgot to close this.

**Comment by eaglgenes101** [comment]
I've experienced this exact problem with benchmarking routines whose run times are measured in nanoseconds. I've tried out all the fixes here (switching to Plotters, changing the confidence interval, even changing to timing method to see if something changes), and the problem of xranges consisting of an empty interval remain. 

For some reason, using a custom measurer that reports a time that is a large multiple of the true value mitigates the problem. Using a custom benchmark iteration routine that runs the actual benchmark large multiple the specified iteration count is much better at avoiding this problem, but if I try to divide this time to get an averaged value rather than a total, it comes right back.

**Comment by dhardy** [comment]
I hit this too with various measurements in the 2-4ns range (not all of them fail; the failures seem to have little variance e.g. `[2.7474 ns 2.7478 ns 2.7482 ns]`).

At a hunch: is this hitting the limits of `f32` when computing the x (time) range of the plot?
