### ISSUE TITLE
Accept (and possibly ignore) --no-capture

### ISSUE THREAD

**Issue by asomers** [bheisler/criterion.rs#404]
The standard test harness captures a test's stdout and throws it away on success.  Specifying `--no-capture` causes it to print the test's stdout regardless of success.  Criterion seems to always print stdout.  It would provide a more consistent user experience for Criterion to capture stdout just like the standard test harness does.  Even if it doesn't, Criterion should still accept `--no-capture` even if it ignores it.  That would allow users to do something like:
```
cargo test --all-targets -- --nocapture
```
Currently, that command will fail in a crate that uses Criterion.
```
error: Found argument '--nocapture' which wasn't expected, or isn't valid in this context
```

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs and thanks for the suggestion.

There isn't a portable way to capture stdout/err in Rust and I don't want to have to maintain a collection of non-portable ways. I honestly have no idea how it's implemented in `libtest`.

However, ignoring the argument isn't hard to do.
