### ISSUE TITLE
Add/change Example

### ISSUE THREAD

**Issue by Pardoxa** [bheisler/criterion.rs#407]
It would be nice to have an example for how to increase the sample size etc. 

It took me longer than I am willing to admit to finally figure out, *where* I should use the corresponding members (e.g., `sample_size`) and it would have helped me a lot, if I found an example like:

```rust
use criterion::{black_box, criterion_group, criterion_main, Criterion};

fn fibonacci(n: u64) -> u64 {
    match n {
        0 => 1,
        1 => 1,
        n => fibonacci(n-1) + fibonacci(n-2),
    }
}

fn criterion_benchmark(c: &mut Criterion) {
    c.bench_function("fib 20", |b| b.iter(|| fibonacci(black_box(20))));
}

criterion_group!(benches, criterion_benchmark);

criterion_group!{
    name = benches;
    config = Criterion::default().sample_size(200);  // changing e.g, sampling size
    targets = criterion_benchmark
}

criterion_main!(benches);
```

**Comment by minghu6** [comment]
> ```rust
> criterion_group!(benches, criterion_benchmark);
> ```

just remove this line

**Comment by minghu6** [comment]
@Pardoxa thank you very much !  I should have wasted many hours of my life without your post!

**Comment by 0o-de-lally** [comment]
+1

**Comment by bheisler** [comment]
Thanks for the suggestion. I've added a section to the [Advanced Configuration](https://bheisler.github.io/criterion.rs/book/user_guide/advanced_configuration.html) page in the user guide with a couple of examples of this.
