### ISSUE TITLE
XML parsing error on violing report

### ISSUE THREAD

**Issue by elichai** [bheisler/criterion.rs#417]
Hi, 
I'm getting errors on some of the violin plots:
Not rendering:
https://htmlpreview.github.io/?https://raw.githubusercontent.com/elichai/bench_linkedlist/6432705da08e16c2d2e7c8c427d90cde7b16218a/rust/target/criterion/Insert%20Back/report/index.html
Plot itself: https://raw.githubusercontent.com/elichai/bench_linkedlist/6432705da08e16c2d2e7c8c427d90cde7b16218a/rust/target/criterion/Insert%20Back/report/violin.svg

Another one:
https://htmlpreview.github.io/?https://raw.githubusercontent.com/elichai/bench_linkedlist/6432705da08e16c2d2e7c8c427d90cde7b16218a/rust/target/criterion/Sum/report/index.html
https://raw.githubusercontent.com/elichai/bench_linkedlist/6432705da08e16c2d2e7c8c427d90cde7b16218a/rust/target/criterion/Sum/report/violin.svg

(other ones do render and work correctly)

EDIT: It seems the problem is some extra weird lines: 
https://github.com/elichai/bench_linkedlist/blob/6432705da08e16c2d2e7c8c427d90cde7b16218a/rust/target/criterion/Sum/report/violin.svg?short_path=106ee30#L361-L364

https://github.com/elichai/bench_linkedlist/blob/6432705da08e16c2d2e7c8c427d90cde7b16218a/rust/target/criterion/Insert%20Back/report/violin.svg?short_path=608e046#L335-L336

Removing those lines fix the svg

**Comment by bheisler** [comment]
Hey, thanks for the bug report and thanks for trying Criterion.rs!

Are you using the gnuplot or plotters backend? Try using `cargo bench -- --plotting backend plotters` or `--plotting-backend gnuplot` to see if the problem happens with the other backend.

**Comment by lemmih** [comment]
Hi @elichai. I haven't been able to replicate this. If it is still a problem for you, please re-open this issue.
