### ISSUE TITLE
Running Criterion benchmarks with Linux and perf

### ISSUE THREAD

**Issue by velvia** [bheisler/criterion.rs#419]
Hey folks, I love Criterion and love what your team is doing for the Rust community!

This is not a problem report, just want to say that if you want a easy to use Docker container with detailed instructions on how to run `perf` with Criterion benchmarks specifically (say on OSX or Windows), feel free to add the following to your docs or wherever you see fit:

https://github.com/velvia/rust-perf-docker

**Comment by bheisler** [comment]
Hey, thanks for the suggestion.

I don't think this is relevant enough to add to the documentation, but thanks anyway!
