### ISSUE TITLE
The way to profile nested functions

### ISSUE THREAD

**Issue by guskovd** [bheisler/criterion.rs#420]
For example:
```
pub fn my_awesome_api_function() {
    // ...
    foreign_function_wrapper();
    // ...
}

// foreign_function, for example in other crate

#[profile_me]
fn foreign_function_wrapper() {
    // ...
    foreign_function();
    // ...
}
```
I need to evaluate the time spent calling ```foreign_function_wrapper```.

But for some reasons I would like to send to criterion.rs my ```my_awesome_api_function``` function

Does criterion.rs allow you to implement something like this?

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs, and thanks for the patience.

I'm not entirely sure I understand what you're asking for.

Criterion.rs cannot measure the fraction of `my_awesome_api_function` that is spent inside `foreign_function_wrapper`, no. If you want to do that, you would need a CPU profiler such as `perf`, not a benchmarking library.

If the wrapper is a public function, then a benchmark could be created to call that directly. Alternately, a benchmark could import and call `foreign_function` itself.

**Comment by bheisler** [comment]
I'm going to close this for now - there doesn't seem to be anything required from Criterion.rs here.
