### ISSUE TITLE
Empty string for benchmark group name errors and fails writing output

### ISSUE THREAD

**Issue by IsakSundeSingh** [bheisler/criterion.rs#421]
Using an empty string for the benchmark group name results in criterion failing to write reports. It seems that it tries to access a folder with an empty name. It errors with (when running `cargo bench` from the project root):
```
Benchmarking /expensive
Benchmarking /expensive: Warming up for 3.0000 s
Benchmarking /expensive: Collecting 100 samples in estimated 5.0000 s (2.6B iterations)
Benchmarking /expensive: Analyzing
Criterion.rs ERROR: error: Failed to access file "/expensive/new": Permission denied (os error 13)
Criterion.rs ERROR: error: Failed to access file "/expensive/new/tukey.json": No such file or directory (os error 2)
Criterion.rs ERROR: error: Failed to access file "/expensive/new/sample.json": No such file or directory (os error 2)
Criterion.rs ERROR: error: Failed to access file "/expensive/new/estimates.json": No such file or directory (os error 2)
/expensive              time:   [1.9061 ns 1.9078 ns 1.9095 ns]
                        thrpt:  [1.9509 GiB/s 1.9527 GiB/s 1.9544 GiB/s]
Found 8 outliers among 100 measurements (8.00%)
  6 (6.00%) high mild
  2 (2.00%) high severe
Criterion.rs ERROR: error: CSV error: No such file or directory (os error 2)
Criterion.rs ERROR: error: Failed to access file "/expensive/report": Permission denied (os error 13)
Criterion.rs ERROR: error: Failed to access file "/expensive/new/benchmark.json": No such file or directory (os error 2)
```

It does not create the `criterion` folder under `target`. 

This is the benchmarking code:
```rust
use criterion::{criterion_group, criterion_main, Criterion, Throughput};
use testy::some_expensive_function;

fn expensive_benchmark(c: &mut Criterion) {
    let mut group = c.benchmark_group("");
    group.throughput(Throughput::Bytes(4));
    group.bench_function("expensive", |b| b.iter(|| some_expensive_function(300)));
}

criterion_group!(
  name = benches;
  config = Criterion::default();
  targets = expensive_benchmark
);

criterion_main!(benches);
```

The whole example project reproducing the bug can be found here:
https://gist.github.com/IsakSundeSingh/3d83a91141e1561b3f8f9b14c92d14bd

I am running on Manjaro 20 but I guess the error (or some variant of it) would happen on all platforms. 

I encountered this because criterion forced me to create a benchmark group if I wanted to specify the throughput. In my case it did not make sense to create a name for the group so I left it empty, leading to these errors. Using a non-empty string for the benchmark group name works fine. It would also be nice if one could specify the throughput without creating a benchmark group.

A note in the documentation that the string cannot be empty should be sufficient, but it would also be good to have checks in place to see if the string is empty and panic with a more descriptive error to the user.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs, and thanks for the bug report!

Yeah, it never occurred to me that anyone might try an empty string. My bad; that will be checked and documented in the next version.

Yes, Criterion.rs requires a `BenchmarkGroup` for configuration. I've found that allowing configuration on single benchmarks (as opposed to requiring a benchmark group and doing the configuration there) isn't a good trade-off - it means Criterion.rs needs a lot of extra complexity - extra types or traits or functions in the public API - but the user code ends up being very nearly the same. This way, benchmark groups with one function are the same as any other group.
