### ISSUE TITLE
Allow the report generation to be disabled

### ISSUE THREAD

**Issue by Marwes** [bheisler/criterion.rs#424]
I frequently run benchmarks to profile parts of my code with `perf`. In those instances I am not interested in the report produced by perf yet perf ends measuring the the report generation as well which can be non-trivial. It would be useful if benchmarks could be run with no (or a minimal) report to maximize the amount of time spent in the actual benchmark as opposed to criterion.

**Comment by bheisler** [comment]
Hello! Thanks for trying Criterion.rs.

Yes, this is what the `--profile-time` argument is for. See the [user guide](https://bheisler.github.io/criterion.rs/book/user_guide/command_line_options.html) for more details.

**Comment by Marwes** [comment]
Whelp, how did I miss that! Thanks!
