### ISSUE TITLE
iter with custom data?

### ISSUE THREAD

**Issue by jagill** [bheisler/criterion.rs#430]
I am trying to benchmark various data structures (RTrees of different forms) and the algorithms that use them.  Given a choice of base data (say, a particular polygon), there is a choice of probe data (points that are within the bounding box of that polygon).  The cost of the algorithm depends significantly on choice of which piece of base data and which piece of probe data.  I'm trying to evaluate how the various data structure/algorithm choices affect the distribution, eg trading off mean time for 90th-percentile time, etc.

1. Given a choice of base data, I'd make a vec of probe data `probes: &[T]` which reasonably samples the space I'm interested in.  I'd like for `iter` to cycle through `probes` in its iterations, something like:
```
b.iter_with_data(data: &[T], f: Fn(T) -> M::Value);
```
This way, I'm sampling through my data, and the final statistics are more meaningful than choosing a single point.

2. If I manage 1, I'd like to actually measure the statistics over the range of base data.  Given `bases: &[S]`, I'd like to
do a non-benchmarked prep step for each `S`, then run the `b.iter_with_data` described above.  Something like:
```
for base in bases {
    let probes = make_probes(base);
    let rtree = make_rtree(base);
    b.iter_with_data(probes, |p| rtree.query(p));
}
```

Is this something I can do with the existing functionality in criterion?

**Comment by bheisler** [comment]
Hey, thanks for the question, and thanks for trying Criterion. Thanks for the patience as well, I suppose you might not still need an answer but maybe someone will find this from Google in the future or something.

For part 1, there isn't anything built in for that per se, but I think it could be done easily enough in user code. Perhaps something like this:
```rust
let probes = make_probes(base);
let rtree = make_rtree(base);

let probes_iter = probes.into_iter().cycle(); // This assumes your probe can be cloned
b.iter_batched(
    move || probes_iter.next().unwrap(),
    |probe| rtree.query(p),
)
```

If your probe can't be cloned then you could still cycle over references to the probes, assuming that you don't need to consume the probe. If you do, then you would have to generate a new probe for each iteration. All of that can be done with [`iter_batched`](https://docs.rs/criterion/0.3.3/criterion/struct.Bencher.html#method.iter_batched). Of course there is also `iter_custom`, which allows you to implement your own measurement loop in any way you wish.

For question 2, it sounds like you want a [`BenchmarkGroup`](https://docs.rs/criterion/0.3.3/criterion/struct.BenchmarkGroup.html). If you're asking for the ability to run over different sets of data and have those contribute to just one measured distribution, that's not currently possible.
