### ISSUE TITLE
Panic due to unclear invariant: is BenchmarkId.function_name required?

### ISSUE THREAD

**Issue by wackywendell** [bheisler/criterion.rs#431]
## Problem

The `BenchmarkId` structure has two `Option` parameters on it: `function_name` and `parameter`. It is unclear whether these are required or optional, and using them in certain ways creates `panic`s from inside `criterion`.

## Details

In `Criterion::bench_with_input`, the `function_name` is labeled as required:

https://github.com/bheisler/criterion.rs/blob/89593658643f9a12949f99f35a6bf906cb4e43c0/src/lib.rs#L1505-L1507

At the same time, there is a public function `BenchmarkId::from_parameter` that can create a `BenchmarkId` without a `function_name`:

https://github.com/bheisler/criterion.rs/blob/89593658643f9a12949f99f35a6bf906cb4e43c0/src/benchmark_group.rs#L446-L453

Using `BenchmarkId::from_parameter` on its own in a benchmark causes a `panic`:

```sh
$ cargo bench
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/wackywendell/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.3/src/lib.rs:1507:26
```

## Example Code

```rust
use criterion::{criterion_group, criterion_main, BenchmarkId, Criterion};

fn power_of_two(n: isize) -> i64 {
    let mut p: i64 = 1;
    for _ in 0..n {
        p *= 2;
    }
    p
}

pub fn criterion_benchmark(c: &mut Criterion) {
    for i in 1isize..=4 {
        c.bench_with_input(BenchmarkId::from_parameter(i), &i, |b, n| {
            b.iter(|| power_of_two(*n))
        });
    }
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```

**Comment by bheisler** [comment]
Good catch, thanks!
