### ISSUE TITLE
Visualize historical data

### ISSUE THREAD

**Issue by PTaylor-us** [bheisler/criterion.rs#432]
I found myself wanting to see how my benchmark test results have changed over time, so I threw together this rust utility (https://github.com/PTaylor-us/criterion-history). Basically, it searches the `target/criterion` folder for folders starting with `BM_` which are created using this powershell script which saves a new baseline every run:
```powershell
$timestamp = Get-Date -Format "yyyyMMddHHmm"
cargo bench -- --save-baseline BM_$timestamp
```
It collects averages the per-iteration duration of each raw.csv file and generates a plot of these average durations over time.

![Annotation 2020-07-30 111704](https://user-images.githubusercontent.com/40178570/88953539-539c6400-d256-11ea-8943-1604ba2a1478.png)

It's all a bit rough, but anyone can feel free to take it and make something more polished/functional.

**Comment by bheisler** [comment]
Hey, thanks for the suggestion. Criterion.rs doesn't have this feature (in fact, doesn't even keep data for long enough to make a useful historical graph) but [cargo-criterion](https://github.com/bheisler/cargo-criterion) does.
