### ISSUE TITLE
output-format doesn't work

### ISSUE THREAD

**Issue by zbraniecki** [bheisler/criterion.rs#433]
[docs](https://bheisler.github.io/criterion.rs/book/user_guide/command_line_options.html) have the following paragraph:

> * To change the CLI output format, use cargo bench -- --output-format <name>. Supported output formats are:
>   * criterion - Use Criterion's normal output format
>   * bencher - An output format similar to the output produced by the bencher crate or nightly libtest benchmarks. Though this provides less information than the criterion format, it may be useful to support external tools that can parse this output.

but when I try to use it:

```
▶ cargo bench -- --output-format bencher
    Finished bench [optimized] target(s) in 0.03s
     Running /projects/icu4x/target/release/deps/icu_locale-909a2cf89fdc665f
error: Unrecognized option: 'output-format'
error: bench failed
```

This format would be useful to plug criterion into https://github.com/rhysd/github-action-benchmark

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs.

Yes, the output format feature was added in order to support that github action. Which version of Criterion.rs are you using? It was only added in 0.3.2, so you may need to update.

**Comment by echeran** [comment]
I upgraded from 0.3.0 to 0.3.3, ran `cargo clean` and `cargo bench` to make sure of the new version and that it works, but I'm still getting the same output when trying to use the new output formatter functionality.  Am I running the command correctly?

```
$ cargo bench -- --output-format bencher
    Finished bench [optimized] target(s) in 0.04s
     Running /usr/home/elango/oss/icu4x/target/release/deps/icu_locale-1844e5dcfef70fab
error: Unrecognized option: 'output-format'
error: bench failed

```

**Comment by bheisler** [comment]
Well, the only other thing I can think of that would cause that is this:

https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options

**Comment by zbraniecki** [comment]
```
[lib]
bench = false
```

seems to fix it!

**Comment by echeran** [comment]
Yep, indeed, [confirmed](https://github.com/echeran/icu4x/pull/4/checks?check_run_id=946185069).  Thanks for the help!
