### ISSUE TITLE
output-format bencher prints Median 

### ISSUE THREAD

**Issue by lambdakappatheta** [bheisler/criterion.rs#434]
Comparing criterion's output (command line) and the generated reports, I noticed that using the default output format (criterion) the value labeled time in the output corresponds to the field Mean in the report whereas using `--output-format bencher `the output corresponds to Median.
I am using criterion as a development dependency:
```
[dev-dependencies]
criterion = "0.3"
```
Currently "0.3" resolves to version 0.3.3.

I have not found any mention of this in the docs, so I started wondering if this is the intended behaviour.

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs. Yes, this is intended. bencher outputs the median value and so does Criterion.rs when it's emulating bencher's output. The two outputs are not quite exactly the same (eg. Criterion.rs presents the median of the bootstrapped sampled where bencher outputs the median of the raw samples, but it's closer than using another statistic would be.
