### ISSUE TITLE
Unneeded nightly requirement in book CI example

### ISSUE THREAD

**Issue by gunvirranu** [bheisler/criterion.rs#436]
On the FAQ page of the user-guide/book, the example CI script requires that the toolchain be nightly. This was needed for the original script (for libtest), but Criterion.rs works fine on stable. The line in question is:
https://github.com/bheisler/criterion.rs/blob/89593658643f9a12949f99f35a6bf906cb4e43c0/book/src/faq.md#L15

**Comment by bheisler** [comment]
I've actually reworked that section of the book to remove the specific script. Thanks for catching this though!
