### ISSUE TITLE
Use both tests and criterion benchmarks with the custom test framework

### ISSUE THREAD

**Issue by mb64** [bheisler/criterion.rs#438]
I would like to use both `#[test]` tests and `#[criterion]` benchmarks in the same crate.

With `#![test_runner(criterion::runner)]`, it fails to compile because the tests are incompatible with criterion:
```
error[E0277]: expected a `std::ops::Fn<()>` closure, found `tests::test::TestDescAndFn`
```

And without it, it fails to compile because the criterion benches are incompatible with cargo's test framework:
```
expected struct `tests::test::TestDescAndFn`, found fn item
```

How can I include both of these in the same crate?  Something like `#[cfg(criterion)]` would be nice, and even better would be to have it somehow automatically incorporated in `#[criterion]` and `#[test]` so that it "just works".

<details><summary>Here's my small not-working example</summary>
<p>

```rust
#![feature(custom_test_frameworks)]
#![test_runner(criterion::runner)]

pub fn fibonacci(n: usize) -> usize {
    if n < 2 {
        1
    } else {
        fibonacci(n - 1) + fibonacci(n - 2)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use criterion::{black_box, Criterion};
    use criterion_macro::criterion;

    #[test]
    fn fib_test() {
        let tests = [1, 1, 2, 3, 5, 8];
        for (n, f) in tests.iter().copied().enumerate() {
            assert_eq!(fibonacci(n), f);
        }
    }

    #[criterion]
    fn fib_bench(c: &mut Criterion) {
        c.bench_function("fib 20", |b| b.iter(|| fibonacci(black_box(20))));
    }
}
```

</p>
</details>

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs! Also, thanks for trying the test-framework; hardly anyone uses that.

Unfortunately, the answer is "you can't". Cargo doesn't allow there to be multiple test frameworks in the same crate; the only reason `#[criterion]` works at all is that `benches/` benchmarks are technically separate crates, with all the limitations that implies. Changing this would require an extension to Cargo's custom-test-framework feature, not Criterion.rs. The RFC for this feature suggests that they do intend to allow replacement of the benchmark harness independently of the test harness, so something like this might be possible in the future, though.

Here's the tracking issue for the custom-test-framework feature: https://github.com/rust-lang/rust/issues/50297
