### ISSUE TITLE
How to interpret change probability values?

### ISSUE THREAD

**Issue by blt** [bheisler/criterion.rs#440]
The [documentation](https://bheisler.github.io/criterion.rs/book/user_guide/command_line_output.html#change) for criterion's change output says:

> This shows a confidence interval over the difference between this run of the benchmark and the last one, as well as the probability that the measured difference could have occurred by chance. 

With the example

```
change: [-38.292% -37.342% -36.524%] (p = 0.00 < 0.05)
Performance has improved.
```

If I understand correctly the confidence interval changes are captured by `[-38.292% -37.342% -36.524%] `? If so, how do we interpret `(p = 0.00 < 0.5)`?

**Comment by bheisler** [comment]
Hey, thanks for the question (and for the patience)!

That number is the [p-value](https://en.wikipedia.org/wiki/P-value) obtained from comparing the two bootstrapped distributions (the saved one from the previous run and the one we just measured). It's used to decide if we can safely conclude that the two distributions are actually different and that the apparent difference is unlikely to have happened due to random noise.

**Comment by blt** [comment]
Great, thanks very much. Makes perfect sense.

**Comment by sboukortt** [comment]
I think it might make sense to reopen this as the current explanation is misleading. In particular, https://bheisler.github.io/criterion.rs/book/analysis.html states:

> The fraction of the bootstrapped T scores which are more extreme than the T score calculated by comparing the two measured samples gives the probability that the observed difference between the two sets of samples is merely by chance.

But that is not what a p-value is. It is a widespread but unfortunately incorrect interpretation. The p-value is the probability that data as extreme _would_ be observed assuming that there is no true difference / that all of the observed difference is pure chance. That is not equal to the probability, given the observed data, that there is no true difference. If the latter is desired then Bayesian inference would seem more appropriate.

Here is some interesting reading on the subject:

- [An investigation of the false discovery rate and the misinterpretation of _p_-values](https://doi.org/10.1098/rsos.140216)

- [Statistical tests, _P_ values, confidence intervals, and power: a guide to misinterpretations](https://doi.org/10.1007/s10654-016-0149-3)

  > To say that chance alone produced the observed association is logically equivalent to asserting that every assumption used to compute the P value is correct, _including the null hypothesis_. Thus to claim that the null _P_ value is the probability that chance alone produced the observed association is completely backwards: The _P_ value is a probability computed _assuming_ chance was operating alone.

- [The ASA Statement on _p_-Values: Context, Process, and Purpose](https://doi.org/10.1080/00031305.2016.1154108)

- [A Dirty Dozen: Twelve _P_-Value Misconceptions](https://doi.org/10.1053/j.seminhematol.2008.04.003)

An immediate improvement would likely be to clarify the current explanation of p-values in the documentation. If an alternative to p-values is further sought then one option might be to compute a Bayesian credible interval of the difference in performance, and see whether it is either completely contained in a certain region of practical equivalence (ROPE), in which case one could say that there is likely not a difference worth bothering about, or completely outside it.
