### ISSUE TITLE
Best way to measure parts of a big function

### ISSUE THREAD

**Issue by Hrodr** [bheisler/criterion.rs#442]
Hello,

Is there a way to measure not a whole function but some parts in it? something like a timer_start/timer_stop would do the thing but I found nothing similar on the docs. 

The other possibility was to break this function and just measure relevant subfunctions but due to the amount of variables involved this solution could be not apropriate.

Thank you

**Comment by bheisler** [comment]
Hello! Thanks for trying Criterion.rs.

Several people have asked me this question, so I've written an answer in the FAQ part of the user guide: https://github.com/bheisler/criterion.rs/blob/master/book/src/faq.md#how-can-i-benchmark-a-part-of-a-function

The short answer is that this can't be done to Criterion.rs' usual accuracy standards, so there is no built-in support for it. However, if you want to (and you're willing to accept some error in the results) you can use `Bencher::iter_custom` and implement your own measurement however you like.
