### ISSUE TITLE
Benchmarks run faster when run individually (cargo bench)

### ISSUE THREAD

**Issue by jjl** [bheisler/criterion.rs#445]
I'm noticing solid differences in some of my benchmarks when they're the only benchmark run. An example here, I've gone from 75ns to 50ns just from not running the other benchmarks.

**Comment by eaglgenes101** [comment]
This is going to appear in any long CPU-intensive task, as modern CPU power controls will throttle the CPU if it reaches a high temperature, to prevent it from cooking from high temperatures. 

That said, a configurable cooldown period after individual benchmark runs might make sense to help mitigate high-temperature throttling.

**Comment by jjl** [comment]
My cpu is definitely not thermal throttling. I have a way overkill cooler
on it (scythe ninja 5 attached with liquid metal)

**Comment by lemmih** [comment]
Hi @jjl. Do you have a minimal example of this behavior?

**Comment by jjl** [comment]
I'm afraid not. There was a huge benchmark that exhibited it but i never got it down to anything minimal. I also haven't observed it in months, so maybe it went away?
