### ISSUE TITLE
Pale blue violin plots are hard to see

### ISSUE THREAD

**Issue by is8ac** [bheisler/criterion.rs#446]
Currently, the violin plots are a very pale blue on white background. This is hard to see. On some of my monitors it is completely invisible. Admittedly my monitors are somewhat cheap, but even on other high quality monitors, they are very pale.

Can the color of the violin plots be configured, or if not, could it be set to some better contrast color?

![hard so see violin plot](https://user-images.githubusercontent.com/8010041/97758872-0cc04380-1abd-11eb-910f-79a1f5bdaa13.png)

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs.

That is an entirely fair point. I'm not even sure why I did it that way. The color of the charts can be configured in https://github.com/bheisler/cargo-criterion, but that turns down the opacity as well. I'll turn the color up to full opacity in the next versions of both projects.

**Comment by bheisler** [comment]
By the way, if you don't want to wait for the next release, I did notice while I was changing the code that cargo-criterion uses 45% opacity instead of Criterion.rs' 25%, so maybe that would help.
