### ISSUE TITLE
Benchmarks are unable to use crate modules annotated with #[cfg(test))

### ISSUE THREAD

**Issue by seanpianka** [bheisler/criterion.rs#448]
**Problem**
Modules annotated with the `#[cfg(test)]` macro cannot be `use`'d by benchmarks, as an unresolved import error is thrown when `$ cargo bench` is run. 

The goal is to re-use test fixtures from the crate's modules in the benchmarks, as they often contain re-useable environment setup logic (which is useful for writing benchmarks!).

**Steps**

1. `$ cargo new --lib mycoolcrate && cd mycoolcrate`
2. Replace the contents of `src/lib.rs` with the following:
```rust
#[cfg(test)]
pub mod tests {
    pub struct Fixture {
        pub value: u8
    }
    impl Fixture {
        pub fn new() -> Self {
            Self { value: 1 }
        }
    }

    #[test]
    fn should_work() {
        let f = Fixture::new();
        assert_eq!(2 + f.value, 3);
    }
}
```
3. Add the following sections to `Cargo.toml`:
```toml
[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "mycoolcrate"
harness = false
```
4. `$ mkdir benches`
5. Add the following contents to `benches/mycoolcrate.rs`:
```rust
extern crate mycoolcrate;
use criterion::{black_box, criterion_group, criterion_main, Criterion};
use mycoolcrate::tests::Fixture;

fn add(a: u8, b: u8) -> u8 {
    a + b
}

fn criterion_benchmark(c: &mut Criterion) {
    c.bench_function("add 1", |b| {
        let fixture = Fixture::new();
        b.iter(|| add(black_box(1), black_box(fixture.value)))
    });
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```
6. Run `$ cargo bench` and see the compiler error:
```rust
error[E0432]: unresolved import `mycoolcrate::tests`
 --> benches/mycoolcrate.rs:3:18
  |
3 | use mycoolcrate::tests::Fixture;
  |                  ^^^^^ could not find `tests` in `mycoolcrate`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `mycoolcrate`
```

**Possible Solution(s)**

I have a workaround that involves nesting modules, where the outer module contains the definition/`impl` of the test fixture, and a nested module is annotated with `#[cfg(test)]` and contains all the unit test cases.

Here is a barebones version of the solution:
`src/lib.rs`:
```rust
pub mod test {
    pub struct Fixture {
        pub value: u8
    }
    impl Fixture {
        pub fn new() -> Self {
            Self { value: 1 }
        }
    }

    #[cfg(test)]
    mod cases {
        use super::Fixture;

        #[test]
        fn should_work() {
            let f = Fixture::new();
            assert_eq!(2 + f.value, 3);
        }
    }
}
```

`benches/mycoolcrate.rs`:
```rust
extern crate mycoolcrate;
use criterion::{black_box, criterion_group, criterion_main, Criterion};
use mycoolcrate::test::Fixture;

fn add(a: u8, b: u8) -> u8 {
    a + b
}

fn criterion_benchmark(c: &mut Criterion) {
    c.bench_function("add 1", |b| {
        let fixture = Fixture::new();
        b.iter(|| add(black_box(1), black_box(fixture.value)))
    });
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```

This nesting of `test` and `cases` keeps the output of `$ cargo test` fairly readable:
```
// This:
test test::cases::should_work ... ok
// Instead of:
test tests::tests::should_work ... ok
```

However, I think it's preferable that the original attempt compiles, if possible, since benchmarking and testing are related concepts.

**Notes**

Output of `cargo version`:
```
$ cargo version
cargo 1.48.0 (65cbdd2dc 2020-10-14)

$ rustup show
<..snip..>
active toolchain
----------------
stable-x86_64-apple-darwin (default)
rustc 1.48.0 (7eac88abb 2020-11-16)

$ system_profiler SPSoftwareDataType
Software:
    System Software Overview:
      System Version: macOS 10.15.7 (19H2)
      Kernel Version: Darwin 19.6.0
      ...
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
```

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs, and thanks for your patience.

Unfortunately, this isn't something Criterion.rs can do. The `#[cfg(test)]` attribute tells the compiler that it should not compile the code at all except for when running tests, so that code simply doesn't exist when running Criterion.rs benchmarks. Changing this would require changes to Cargo.

See: https://users.rust-lang.org/t/what-are-the-rules-for-cfg-test/54122/2

**Comment by seanpianka** [comment]
I opened this as an issue with cargo several weeks ago, and [they responded suggestions](https://github.com/rust-lang/cargo/issues/8897#event-4053479032).
