### ISSUE TITLE
Bench function inside a thread

### ISSUE THREAD

**Issue by lemunozm** [bheisler/criterion.rs#451]
Hi, 

I have a test with several threads. I would want to bench some minor parts that are inside of these threads. Actually, I am getting an error because the criterion reference can not be sent between threads safely. There is some known workaround to archive my target?

I want to remark that the test needs to have mandatory these threads to works. There is some way to make the benches in this scenario?

Thank you so much!

**Comment by bheisler** [comment]
Hey, thanks for trying Criterion.rs, and thanks for the patience.

My advice would be to expose those inner functions on their own and benchmark them directly, without the usual threads. It's not really possible to measure the time of a _part_ of a function accurately, or at least not if that function's runtime is small compared to the system clock's resolution.

If it's really not possible to separate the functions to be measured from their threads, then it's not that useful to measure them without their threads; the callers of your threaded function care about the performance of the threaded function, not just that small portion of it.

However, if you insist on doing that anyway, you can always use `Bencher::iter_custom` and measure the time however you want to. Please be aware that there will be limits to how accurate that measurement can be.

**Comment by lemunozm** [comment]
Thanks for your answer! 
I will try to re-think the tests to try to avoid measure into the thread.
