### ISSUE TITLE
Programmatically configure color output

### ISSUE THREAD

**Issue by IceSentry** [bheisler/criterion.rs#452]
I'm using criterion to benchmark my code for advent of code. I want to be able to only bench a specified day without duplicating that logic in the bench so I can't just use cargo bench. Here's the full repo https://github.com/IceSentry/advent_of_code_2020

The relevant part is here
```rust
fn bench<'a, S: Solver>(day: u8, input: &'a str) -> Result<()> {
    let mut criterion = criterion::Criterion::default().without_plots();
    let mut group = criterion.benchmark_group(format!("Day {}", day));

    group.bench_with_input("parser", &input, |b, i| {
        b.iter_with_large_drop(|| S::parse(i));
    });

    let input = S::parse(input)?;

    group.bench_with_input("part 1", &input, |b, i| {
        b.iter_batched(|| i, S::part1, criterion::BatchSize::SmallInput)
    });

    group.bench_with_input("part 2", &input, |b, i| {
        b.iter_batched(|| i, S::part2, criterion::BatchSize::SmallInput)
    });

    Ok(())
}
```

Specifically, when creating criterion::Criterion::default() the default CliReport enable_color is set to false and there's no way to change this, but I would like to have a colored output with this setup. I might be missing something but I can't find a way to enable color output since I don't use configure_with_args.

**Comment by remi-dupre** [comment]
A quick flexible way of doing it would be to move the logic of `configure_with_args` to a new method `configure_with_vec` which could take a vector built at run time as parameter.

**Comment by IceSentry** [comment]
Yeah, that could work, I would even be willing to make a PR for that, but I'd rather wait to know the opinion of a maintainer if they even want to support that style of configuration.

**Comment by bheisler** [comment]
Hey, thanks for the suggestion! Thanks for the patience too, I suppose this is a bit late now that Advent of Code is over.

I have to say I'm leaning towards "no". This is a very unusual way to run Criterion, and I'm reluctant to add API surface for such a niche use case. I'm not sure I fully understand why you're doing it this way? It seems like you could accomplish the same goal with benchmarks structured in the normal way - running subsets of benchmarks is already supported by `cargo bench`; Criterion even allows using regular expressions to filter the benchmarks to run. Why wouldn't `cargo bench -- "day 1/part 1"` work for you?

**Comment by IceSentry** [comment]
The issue is mostly about using the same code for selecting the day and selecting the benchmark since I'm already parsing the cli argument and I'm generating a lot of this with macros. I also already generate a main function similar to the https://github.com/remi-dupre/aoc crate by @remi-dupre. 

Considering it's already possible to run the benchmark like this, I'm not sure why it wouldn't be possible to pass the same flags you could pass to the cli version. I understand not wanting to increase the surface, but it's not really a new feature, it would just be a new way to toggle an already existing feature. 

It is very possible that I simply misunderstand how to configure criterion, but currently the simplest way for me to do what I want is to manually call criterion and only using the part that actually runs the benchmark.

**Comment by bheisler** [comment]
I'm sorry, I still don't understand. Could you explain in more detail why just using Criterion's built-in benchmark filtering wouldn't do what you want?

**Comment by IceSentry** [comment]
It's not that it wouldn't work, it's just that it would require changing stuff while my setup already works and can run all my benchmarks with no issue (other than the lack of color). The only reason I don't have colors is because the relevant flag is private. 

I had some issues when trying to run it with configure_from_args() although this is most likely on my side.

I understand if you don't want to add this feature and it's not like it would be that much trouble to make it work on my side. It's just that my setup already works and I was surprised that I could do all of this but the color is turned off by default and this can't be modified programmatically, but the flag already exists. I could probably make it work fairly easily, but my current setup uses a single function which was nice and simple.

The real issue is that it was a bit confusing that a feature that is modifiable from the cli can't be modified programmatically.

**Comment by bheisler** [comment]
Fixed.
