### ISSUE TITLE
Adding docs on using Criterion in Github Action

### ISSUE THREAD

**Issue by szunami** [bheisler/criterion.rs#455]
Hey all, love this crate!

I think it would be great to extend this portion of the book:

https://github.com/bheisler/criterion.rs/blob/89593658643f9a12949f99f35a6bf906cb4e43c0/book/src/faq.md#how-should-i-run-criterionrs-benchmarks-in-a-ci-pipeline

to describe how to use Criterion in a Github Actions workflow. For what it's worth, I wrote up my experience here: https://szunami.github.io/blog/2020/12/19/criterion.html

I would be happy to contribute this to the book, let me know if that is welcome.

**Comment by bheisler** [comment]
Hey, thanks for the suggestion!

To be honest, I've always been a bit uncomfortable having that section there at all. Wall-clock benchmarks are just not reliable in virtualized cloud CI environments, and statistical analysis can only mitigate that at best. I have been experimenting with a completely different approach with https://github.com/bheisler/iai , which runs single-shot benchmarks in Cachegrind and should be much more robust to virtualization than wall-clock time benchmarks.

Once Iai is a bit more ready I think I'll probably remove that section from the book entirely in favor of encouraging people to use Iai for their benchmarks in the cloud instead.

**Comment by szunami** [comment]
Makes sense, I'll keep an eye out for ^! Looks cool.
