### ISSUE TITLE
--output-format option broken?

### ISSUE THREAD

**Issue by mabbamOG** [bheisler/criterion.rs#458]
On `criterion = "0.3"` and MacOS BigSur,

```bash
$ cargo bench -- --output-format bencher 
    Finished bench [optimized] target(s) in 0.07s
     Running target/release/deps/***-***
error: Unrecognized option: 'output-format'
error: bench failed
```

**Comment by bheisler** [comment]
Hello! Thanks for trying Criterion.rs.

See [here](https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options) for more information about this.

**Comment by bheisler** [comment]
I'm going to close this for now but please feel free to reopen if this is actually a different problem.
