### ISSUE TITLE
Build errors on my system (with workspaces)

### ISSUE THREAD

**Issue by radrow** [bheisler/criterion.rs#460]
I have set everything up like in Getting Started section, but when I run `cargo bench` I am getting a wall of errors like
```
error[E0433]: failed to resolve: could not find `__private` in `_serde`
   --> /home/radek/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.3/src/estimate.rs:159:5
    |
159 |     pub mean: Estimate,
    |     ^^^ could not find `__private` in `_serde`

error[E0433]: failed to resolve: could not find `__private` in `_serde`
   --> /home/radek/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.3/src/estimate.rs:157:28
    |
157 | #[derive(Debug, Serialize, Deserialize, Clone)]
    |                            ^^^^^^^^^^^ could not find `__private` in `_serde`
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
What could go wrong? My `Cargo.toml`:
```
[workspace]
members = [
    "solver",
    ...
]
```
And `solver/Cargo.toml`:
```
[package]
name = "solver"
version = "0.1.0"
authors = [
  ...
]
edition = "2018"

[dependencies]
...

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "bruteforce"
harness = false
```

**Comment by radrow** [comment]
It does work on a similar project that doesn't use workspaces

**Comment by bheisler** [comment]
Hello! Thanks for trying Criterion.rs!

I have to say, I've never seen anything like this before. I could only guess that something very strange is happening with the dependencies. Could you share a reproduction case? That would help to diagnose it.

**Comment by radrow** [comment]
Ah, nevermind. I tried to reproduce it on some small example but couldn't fall in these errors again. So I nuked my `target` and it worked

**Comment by snylonue** [comment]
@bheisler same issue
I checkouted branches several times before suddenly meeting the problem
seems to be a serde error (teloxide/teloxide#328, https://users.rust-lang.org/t/serde-compatibility-broken/54041)
