### ISSUE TITLE
v0.3.4 is missing a git tag, github release and proper changelog

### ISSUE THREAD

**Issue by badboy** [bheisler/criterion.rs#463]
https://crates.io/crates/criterion/0.3.4

Released 2021-01-24.

The changelog isn't updated, there's no git tag or github release available.
From the `Unreleased` section of the changelog whatever is there should definitely not be a patch release.

Please update the changelog and create a proper tag at least.

**Comment by bheisler** [comment]
Ah, you're right. I did forget to push that change and make the tag. My bad. Should be fixed now.

**Comment by badboy** [comment]
Thanks!
