### ISSUE TITLE
Can I launnch the same criterion program many times simultaneously?

### ISSUE THREAD

**Issue by CXWorks** [bheisler/criterion.rs#473]
Hi,

I'm new to criterion and I found cirterion will generate an executable binary when do benching in cargo.

My question is can I launch this binary many times simultaneously? Will this lead to crash? (I encountered some SEGV errors but not sure if it's caused by my code or my misuse)

Thanks!

**Comment by lemmih** [comment]
Hi @CXWorks. You should be able to spawn as many benchmark processes as you want without crashes. Criterion will never (bar any bugs) crash with a segmentation fault.

**Comment by bheisler** [comment]
They shouldn't crash with a segmentation fault, no. If the processes are running the same benchmarks in the same repository the independent processes will all try to overwrite the reports and saved measurements on the file system and that may produce unexpected benchmark results. The additional CPU usage may add noise to the measurements.

I wouldn't _recommend_ running many benchmarks in parallel, but they shouldn't segfault.

**Comment by CXWorks** [comment]
Thx for your response!
