### ISSUE TITLE
v0.3.5 breaks MSRV using `matches!` macros

### ISSUE THREAD

**Issue by JohnTitor** [bheisler/criterion.rs#509]
I'm not sure if this crate follows MSRV but #491 introduced `matches!` macros and v0.3.5 has bumped up MSRV (1.41).

**Comment by lemmih** [comment]
Hi @JohnTitor. As mentioned in the README, criterion supports the last three minor releases of rust. Support for older versions may be dropped without it being considered a breaking change. I'm open to discussing a policy change if this gets in the way of your workflow, though.
