### ISSUE TITLE
CONTRIBUTING.md doesnt explain which branch to make PRs against.

### ISSUE THREAD

**Issue by rukai** [bheisler/criterion.rs#518]
PRs seem to be going against the 0.4 branch so I guess thats what we are supposed to do.
But this should be documented explicitly

**Comment by lemmih** [comment]
PRs with breaking changes go to 0.4 (ie the unreleased branch), PRs without breaking changes go to 0.3 (ie master). But you don't really have to worry about it when making the PR. It can be decided later during review whether it is a breaking change or non-breaking change.
