### ISSUE TITLE
Code throws an error when running in Criterion but not when run by cargo

### ISSUE THREAD

**Issue by Nateckert** [bheisler/criterion.rs#529]
Hi,

I use criterion (thanks for that crate, it is great !) to benchmark a solver I wrote (https://crates.io/crates/newton_rootfinder)
and I stumbled upon a weird issue : a code panics (on a unwrap()) when run on criterion but not when I run it with cargo:

https://github.com/Nateckert/newton_rootfinder/tree/criterion_error

To reproduce it:
- `cargo bench --all-features`, which will run `benches/square2/static_types.rs`
- `cargo run --all-features`, which will run `src/bin/main.rs`

I wanted to debug it by starting to reproduce what criterion is doing in script, but I didn't know how to mimic the criterions functions. If you can point me towards the right direction, I could perform such a debug

Regards,

**Comment by lemmih** [comment]
Criterion just runs your code snippet a bunch of times. In your case, it'll run `solve_problem(black_box(&mut user_model), black_box(&mut rf))` repeatedly for a few seconds. Try putting all your code inside the benchmark iterator.

Also, the way you use `black_box` has no effect. It's a difficult function to use and most of the time you're better off not worrying about it.

**Comment by Nateckert** [comment]
Ok I figured it out ! Thanks for the tip.

Everything is working fine with criterion, it is just that my struct has as method that shouldn't be called twice.
I am going to change the design to mark it as such.

The only issue I have is that it is this method I would actually like to benchmark.
Basically, the struct `RootFinder` has the methods `RootFinder::new()` and `RootFinder::solve()`.

I am not interested in benchmarking the new operation but only the solve (but this one should only be called once). Is there any way for me to achieve that or should I benchmark new + solve and then substract the results of just benchmarking new().

Thanks a lot !
