### ISSUE TITLE
`serde_cbor` is unmaintained (RUSTSEC-2021-0127)

### ISSUE THREAD

**Issue by crepererum** [bheisler/criterion.rs#534]
As per [RUSTSEC-2021-0127](https://rustsec.org/advisories/RUSTSEC-2021-0127) `serde_cbor` is unmaintained. Would be nice if it could be replaced by [`ciborium`](https://crates.io/crates/ciborium) or [`minicbor`](https://crates.io/crates/minicbor).

I can take care of that, but I've seen #496 is currently in progress so I'm wondering if this should target `master` or `version-0.4`?

**Comment by jhpratt** [comment]
Looks like #496 is progressing somewhat slowly (just an observation, not a complaint), so this should probably be done on its own. Though realistically I don't see it as a huge urgency to change, as there's no indication the crate doesn't still work.

**Comment by briansmith** [comment]
I think this should be closed since it was fixed by PR #560.
