### ISSUE TITLE
Line chart is unreadable (should use log scale)

### ISSUE THREAD

**Issue by SUPERCILEX** [bheisler/criterion.rs#545]
[lines-svg.zip](https://github.com/bheisler/criterion.rs/files/7802212/lines-svg.zip)

The chart should use a log scale because the lower values are too small to be compared.

**Comment by FedericoStra** [comment]
I think you can set a log scale with

```rust
let plot_config = PlotConfiguration::default().summary_scale(AxisScale::Logarithmic);
group.plot_config(plot_config);
```

**Comment by SUPERCILEX** [comment]
That works, thank you! I feel like this could probably be detected automatically, but eh, this is good enough.
