### ISSUE TITLE
Upgrade to clap3

### ISSUE THREAD

**Issue by matklad** [bheisler/criterion.rs#571]
Clap is a sizable dep, and as the ecosystem is migrating to 3.0, compiling both 2.0 and 3.0 becomes suboptimal :)

**Comment by hhirtz** [comment]
See #543

**Comment by bheisler** [comment]
Hello! Thanks for the suggestion. The version 0.4 of `criterion-rs` already depends on `clap` v3.1. We're also looking at replacing `clap` with something else (something lighter-weight).
