### ISSUE TITLE
Negative-time benchmarks

### ISSUE THREAD

**Issue by asomers** [bheisler/criterion.rs#573]
Running my benchmark with criterion, I consistently observe two problems:
* A bimodal distribution of execution times.  This might be due to the CPU's turbo boost, even though I tried to disable that.
* A backwards jump in the Total Sample Time.  This means that one batch of iterations must've taken negative time.  You can see it in the attached graph.  It's not a plotting error, because it's visible in the CSV files too.

At first I suspected an OS bug.  So I wrote a C program that calls `clock_gettime(CLOCK_MONOTONIC)` in a tight loop, checking for any backwards-jumps.  Then I executed that program and criterion at the same time, pinned to the same core.  The C program never sounded any alarms, even though the benchmark shows this negative-time behavior about nine times out of every ten.

What could be causing this?  I see that Criterion doesn't measure the execution time for every iteration, but rather for batches of iterations.  Could this behavior be caused by some kind of error in the per-batch analysis?

FreeBSD 14.0-CURRENT amd64 Ryzen 5950X.

![regression](https://user-images.githubusercontent.com/129721/164983480-d287dfec-5ab5-4087-bca3-3f350b3629cb.svg)

**Comment by theJasonFan** [comment]
@asomers I was seeing this too in a large benchmark and I too was very confused. I did a little bit of digging and I think I got to the bottom of this.

The (x,y) pair for any point in the plot above:
-  Is *not* the total number if iterations run by criterion *up until 
-  But instead is the total time elapsed for *one* sample *with x iterations*

Essentially, criterion picks a point x-axis to sample and runs x number of iterations and reports the elapsed time for *that* sample that runs for x iterations.

Criterion also collects samples from in order from left-to-right on the x-axis above. Hence, the plot above is entirely possible if a CPU is running a bit faster later on in the benchmarks.

Perhaps @bheisler can chime in / confirm?

**Comment by asomers** [comment]
That makes perfect sense, @theJasonFan !  I think you've nailed it.  The issue looks even more clear if I run the same benchmark but with unrestricted Turbo Boost.
![regression](https://user-images.githubusercontent.com/129721/187557008-df63d724-6d25-4eb7-a97b-74b671c396dd.svg)

**Comment by theJasonFan** [comment]
@asomers cool, I think you can close the issue.

@bheisler do you think it would be helpful to clarify this in the docs somewhere?

**Comment by bheisler** [comment]
Hey, thanks for your patience. Yes, what theJasonFan said above is correct - Criterion-rs measures a linearly-increasing number of iterations for each sample. This is convenient because we can then fit a line to the resulting data points as another means of estimating the time per iteration in addition to simply dividing sample times by iteration counts. This is noted in the documentation section on analysis, so I don't think it needs to be added anywhere else.
