### ISSUE TITLE
Configuring and running multiple benchmarks

### ISSUE THREAD

**Issue by twitu** [bheisler/criterion.rs#575]
Firstly thanks for this awesome crate, it's super useful and actually makes benchmarking fun.

However I'm facing an issue with configuring multiple benchmarks so I wanted to ask here. I've checked previous issues and checked documentation but couldn't find an answer.

I want to criterion and iai bench the same function. Since both create a `main` function they cannot exist in the same file, so now I have two files in `benches` directory.
```
benches/
  iai_fixed_precision_benchmark.rs
  criterion_fixed_precision_benchmark.rs
```
1. If I just run `cargo bench` without any changes to `Cargo.toml` it auto detects the benches and runs them but in a weird way. It's almost like they're run like unit test and benching information isn't produced.

  ```
  Running unittests (target/release/deps/criterion_fixed_precision_benchmark-808c6261ea7f68d4)
  
  running 0 tests
  
  test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
  
       Running unittests (target/release/deps/iai_fixed_precision_benchmark-57afbb836f920742)
  
  running 0 tests
  
  test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
  ```
2. So then I add the `[[bench]]` key to `Cargo.toml` but it can take only 1 name. So only one bench runs properly, the other still doesn't show the output.

```
[[bench]]
name = "criterion_fixed_precision_benchmark"
harness = false
```

```
     Running unittests (target/release/deps/criterion_fixed_precision_benchmark-808c6261ea7f68d4)
<-- snip -->
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) low mild
  2 (2.00%) high severe

     Running unittests (target/release/deps/iai_fixed_precision_benchmark-57afbb836f920742)

running 0 tests
```

**Is there anyway to configure multiple benches to run properly?** It's not just a criterion, iai thing, there could be a use case for multiple criterion benches that are not grouped and in separate files.

I'm grateful for any help.

**Comment by twitu** [comment]
Just wanted to bump this. If there are any workarounds or solutions?

**Comment by lemmih** [comment]
You can specify multiple benchmark targets. https://doc.rust-lang.org/cargo/reference/cargo-targets.html

**Comment by twitu** [comment]
Multiple benchmarks can be given as.

```
[[bench]]
name = "something"
harness = false

[[bench]]
name = "something_else"
harness = false
```
