### ISSUE TITLE
Throughput documentation clarification

### ISSUE THREAD

**Issue by SephVelut** [bheisler/criterion.rs#580]
I'm raising this issue because It's not clear to me from the documentation by what metric group.throughput() is making it's measurement. I have the following code
```rust
        let mut group = c.benchmark_group("Search Bench");
        group.throughput(criterion::Throughput::Elements(1000));                                                                                 
        group.bench_with_input(BenchmarkId::from_parameter(1000), &1000, |b, &size| {                                                                                     
            b.iter(|| std::iter::repeat(1u8).take(1000).collect::<Vec<_>>());                                                        
        });                      
```

Reports this time `time:   [20.660 ns 20.710 ns 20.758 ns]`. Okay sure. Then reports this for throughput `thrpt:  [48.173 Gelem/s 48.286 Gelem/s 48.402 Gelem/s]`. What? 48 iterations per second? As in how many iterations the iter::repeat makes? That's definitely not true. Or how many iterations the `b.iter` bench makes? That's not true either. Criterion reports that it ran hundreds of millions of iterations of the benchmark itself.

`Benchmarking Search Bench/1000: Collecting 100 samples in estimated 5.0001 s (240M iterations)`

**Comment by V0ldek** [comment]
48.286 Gelem/s means that 48 _billion_ elements are processed per second.  Note the large G in front -- that's gigaelements This tracks:

20.710ns = 0.00000002071s
1000 elements / 0.00000002071s =~ 48,285,852,245.29 elem/s =~ 48.286 Gelem/s
