### ISSUE TITLE
Disable html reports warning without enabling it

### ISSUE THREAD

**Issue by KarelPeeters** [bheisler/criterion.rs#584]
When I currently run `cargo bench` with criterion set up as follows:

```toml
criterion = { version = "0.3.5", default-features = false, features=["cargo_bench_support"] }
```

I get this warning:

> WARNING: HTML report generation will become a non-default optional feature in Criterion.rs 0.4.0.
This feature is being moved to cargo-criterion (https://github.com/bheisler/cargo-criterion) and will be optional in a future version of Criterion.rs. To silence this warning, either switch to cargo-criterion or enable the 'html_reports' feature in your Cargo.toml.

Is there a way to get rid of this warning by _disabling_ html reports instead of enabling them?

**Comment by bheisler** [comment]
Hello!

Currently there is no way to silence that warning without either enabling the HTML reports or running in `cargo-criterion`. If you want to suppress report generation, my recommendation would be to use `cargo-criterion` and pass it the `--plotting-backend disabled` option, or wait until version 0.4. In version 0.4, you'll be able to disable generating reports just by not enabling the `html_reports` feature.
