### ISSUE TITLE
Cargo build of project with Criterion triggers Kaspersky Anti-Virus events

### ISSUE THREAD

**Issue by mikeHag** [bheisler/criterion.rs#588]
I know the title is vague because I don't have an understanding of whether the problem is with Criterion, the method Criterion uses to build or Kaspersky.  I know that Kaspersky starts acting up when I include Criterion in cargo.toml and that the errors are around a build script that I assume is related to Criterion given the apparent causality.  The Kaspersky version is 21.3.10.391.

I have found reports of build scripts triggering exceptions on both different anti-virus programs and different rust crates.  I am not clear on how I can verify that the reports are false positives. I hate to start blindly setting exclusions. So, I am looking for comments/suggestions.  I am happy to supply additional information.

Here is a picture of the file actions from Kaspersky
![Reports 6_29_2022 7_38_07 PM](https://user-images.githubusercontent.com/36011050/176564289-d4cdf62b-de4e-45f5-ba0e-6ed659d381e7.png)

**Comment by mikeHag** [comment]
I was using stable rust 1.61.0.  I saw another similar report here: https://issuehint.com/issue/prisma/prisma-engines/2601.  The issue resolved by moving from 1.57.0 to 1.58.0.  My problem disappeared after an update to 1.62.0.

I am unsure how many other crates may have this problem, but I had also encountered it on 1.57.0 with regex.

**Comment by bheisler** [comment]
That is wild. Thanks for the report, but honestly, I'm not sure what I can even do about this. The build script in question seems to belong to the `memchr` crate which is used by many projects in the Rust ecosystem and is written by a well-known and trusted author so it seems unlikely to be malicious.

The version-0.4 branch does remove the dependency on `memchr` though. Perhaps that could serve as a workaround?
