### ISSUE TITLE
MSRV busted by plotters

### ISSUE THREAD

**Issue by aganders3** [bheisler/criterion.rs#592]
Hello - a new release of `plotters` 0.3.2 has set `edition: 2021` effectively raising the MSRV for that crate and this one to (at least) 1.56.

It would be nice to keep the current MSRV, so I propose pinning `plotters` to `0.3.1` for now. I am happy to make a PR for this, but I noticed the contributing guidelines advise against PRs to update dependencies.

**Comment by aganders3** [comment]
Never mind! I think I was just misunderstanding package specs...

**Comment by bheisler** [comment]
I only just noticed this myself, yes. You can configure your Cargo.toml file to keep using `plotters` 0.3.1 if that helps. Criterion-rs's MSRV policy is to explicitly support only the last three major versions of rustc, though, which means 1.59 at the moment.

(For the record, I wouldn't be opposed to pull requests to change the dependencies to actually solve problems, I just didn't want a bunch of small dependency bumps cluttering up the commit history when I could easily do them all in one go before release)
