### ISSUE TITLE
Dependabot warnings for crossbeam-utils and regex

### ISSUE THREAD

**Issue by carlosbalbora** [bheisler/criterion.rs#603]
I am using `criterion.rs` 0.3.6 that it uses `crossbeam` v0.8.6 (via `rayon` 1.5.1) and regex `regex` v1.5.4. It throws high level warnings:  

- error for crossbeam https://github.com/crossbeam-rs/crossbeam/pull/781
- error for regex https://groups.google.com/g/rustlang-security-announcements/c/NcNNL1Jq7Yw
But bugs can be fixed if we update rayon and regex (I can do the PR myself)

**Comment by carlosbalbora** [comment]
https://github.com/bheisler/criterion.rs/pull/604 <- my PR

**Comment by bheisler** [comment]
Thanks for the info and the pull request, but my policy is to not accept pull requests that only update dependency versions.

I considered making an exception but it seems that Cargo already happily pulls in and uses the new versions of those two dependencies even with the Criterion-rs specifying a dependency on the old version, so there doesn't seem to be any particular urgency as users can simply update their lockfiles and get a newer version of regex and rayon.
