### ISSUE TITLE
HTML Report Not Generated, Gnuplot Installed

### ISSUE THREAD

**Issue by naftulikay** [bheisler/criterion.rs#618]
I'm following the getting started guide and I am not seeing HTML reports being generated, in spite of `gnuplot` existing and being on `PATH`. I'm on Linux for what it's worth, amd64.

I'm on `criterion` `0.4.0` according to Cargo.lock, `criterion-plot` `0.5.0`. 

Relevant sections of `Cargo.toml`:

```toml
[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "example"
harness = false
```

And my benchmark, at `benches/example.rs`:

```rust
use criterion::{black_box, criterion_group, criterion_main, Criterion};

fn fibonacci(n: u64) -> u64 {
    match n {
        0 => 0,
        1 => 1,
        n => fibonacci(n - 1) + fibonacci(n - 2),
    }
}

fn criterion_benchmark(c: &mut Criterion) {
    c.bench_function("fib 20", |b| b.iter(|| fibonacci(black_box(20))));
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```

As you can see, I'm following the getting started guide exactly. In fact, my repository is open source: [github.com/naftulikay/rust-fuzzy-datetime](https://github.com/naftulikay/rust-fuzzy-datetime/tree/0d75594846315db9623388009cb181e087ba9bbc).

Here's what's in `target/criterion`:

```text
target/criterion/
└── fib 20
    ├── base
    │   ├── benchmark.json
    │   ├── estimates.json
    │   ├── sample.json
    │   └── tukey.json
    └── new
        ├── benchmark.json
        ├── estimates.json
        ├── sample.json
        └── tukey.json

3 directories, 8 files
```

Proving `gnuplot` is there:

```shell
$ which gnuplot
/usr/bin/gnuplot
```

I'm running `cargo bench`, and I see the JSON but no HTML report being generated.

Is there a command line argument I need to be passing?

**Comment by Alfred-Mountfield** [comment]
I believe you need to enable the "html_reports" feature. I don't see this documented anywhere. At least I cannot find an updated User Guide for 4.0.

**Comment by naftulikay** [comment]
@Alfred-Mountfield confirming that this does the trick, closing.

**Comment by frederikhors** [comment]
Same here. Can we please add in docs?
