### ISSUE TITLE
Update docs & examples to use builtin `bench_black_box` (1.66 stable)

### ISSUE THREAD

**Issue by tgross35** [bheisler/criterion.rs#633]
`std::hint::bench_black_box` will be stable in 1.66 (2022-12-15 stable date) and I believe it may supercede the need for `criterion:: black_box` in some ways. It may be worth upating the docs to indicate this, and possible tradeoffs if any.

Docs: https://doc.rust-lang.org/std/hint/fn.black_box.html

**Comment by frewsxcv** [comment]
1.66 is now released and `black_box` is now stable

https://blog.rust-lang.org/2022/12/15/Rust-1.66.0
