### ISSUE TITLE
reports (plots/graphs) not created

### ISSUE THREAD

**Issue by sjaghori** [bheisler/criterion.rs#652]
With version 0.4.0, the report folder is not created.

**Comment by phaile2** [comment]
I believe that plotting has been moved to the cargo-criterion crate you need to run `cargo install cargo-criterion`, and run benchmarking using `cargo criterion`, per https://crates.io/crates/cargo-criterion

**Comment by AntoniosBarotsis** [comment]
@sjaghori I'm not sure if this is relevant but maybe check #638 just in case 😅
