### ISSUE TITLE
Criterion benchmark not running

### ISSUE THREAD

**Issue by jacklund** [bheisler/criterion.rs#660]
I've got a benchmark for some code in `benches/herding.rs` that looks like this:

```rust
use criterion::{criterion_group, criterion_main, Criterion};
use my_crate::herding::*;
use my_crate::md::*;

pub fn criterion_benchmark(c: &mut Criterion) {
    c.bench_function("DiamondStructure generate", |b| {
        b.iter(|| DiamondStructure::generate(5, 4, &[0u8; BLOCKSIZE]))
    });
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```

However when I run `cargo bench`, this is what I get:

```
     Running benches/herding.rs (target/release/deps/herding-44a10c5c6aa35250)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

From the docs it looks like this is just what I should be doing, but clearly I'm doing something wrong here. I haven't been able to find anyone else having the same issue. Can you tell me what I'm doing wrong here?

I'm running `rustc 1.67.1 (d5a82bbd2 2023-02-07)` and `cargo 1.67.1 (8ecd4f20a 2023-01-10)`, and criterion 0.4.0.

Thanks!

-Jack

**Comment by Shitaro** [comment]
Have you encountered this problem when benchmarking a package included in the workspace?
I face exactly the same problem as you reported.

I created a package called `my_bench` in a project called `my_bench_workspace`.
Then I added the `benches` directory to the `my_bench` directory and the rest is done according to the criterion documentation, adding files to benchmark the Fibonacci sequence. 

```rust
// my_bench/benches/benchmark.rs

use criterion::{black_box, criterion_group, criterion_main, Criterion};

fn fibonacci(n: u64) -> u64 {
    match n {
        0 => 1,
        1 => 1,
        n => fibonacci(n - 1) + fibonacci(n - 2),
    }
}

fn criterion_benchmark(c: &mut Criterion) {
    c.bench_function("fib 20", |b| b.iter(|| fibonacci(black_box(20))));
}

criterion_group!(benches, criterion_benchmark);
criterion_main!(benches);
```

The directory structure is the following:

```
my_bench_workspace
├── Cargo.lock
├── Cargo.toml
├── my_bench
│   ├── Cargo.toml
│   ├── benches
│   │   └── benchmark.rs
│   └── src
│       └── lib.rs
└── src
    └── lib.rs
```

When I run `cargo bench`, I get exactly the same results as @jacklund did.

```sh
$ cargo bench
   ........
   ........
   Compiling criterion v0.4.0
    Finished bench [optimized] target(s) in 23.76s
     Running unittests src/lib.rs (target/release/deps/my_bench-c8a5743e75a95334)

running 1 test
test tests::it_works ... ignored

test result: ok. 0 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running benches/benchmark.rs (target/release/deps/benchmark-194f0cdd6b991aaf)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

## Env

- Debian GNU/Linux 10 (buster)
- rustc 1.67.1 (d5a82bbd2 2023-02-07)
- criterion = "0.4.0"

## Contents of the other files

### `my_bench/Cargo.toml`

```toml
[package]
name = "my_bench"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "benchmark"
barness = false

[dev-dependencies]
criterion = "0.4.0"
```

### `Cargo.toml`

```toml
[workspace]
members = ["my_bench"]
```

**Comment by AntoniosBarotsis** [comment]
@Shitaro @jacklund If you guys are running benchmarks in workspaces, try `cd`ing into the crate that defines the benchmarks before running `cargo bench`. I didn't try your example but I have written benchmarks in a workspace project, if this doesn't work I'll share them and maybe you can figure out why. Everything else seems to be the same at first glance though.

Edit: @Shitaro You seem to have misspelled `harness` in `my_bench/Cargo.toml` :)

Edit 2: Hm, running it in the root as well seems to work for me, nevermind. You can take a look at my project [here](https://github.com/AntoniosBarotsis/qr-rs), the benchmark is inside of the `lib` crate, can't seem to figure what you guys did differently... Maybe it works for me cause I've already built it once? Not sure.

**Comment by Shitaro** [comment]
> Edit: @Shitaro You seem to have misspelled harness in my_bench/Cargo.toml :)

Thank you @AntoniosBarotsis for catching my very very naive typo😭 
And, well, my sample code worked fine after I fixed it!

```sh
$ cargo bench
   ........
   ........
   Compiling criterion v0.4.0
    Finished bench [optimized] target(s) in 28.26s
     Running unittests src/lib.rs (target/release/deps/my_bench-c8a5743e75a95334)

running 1 test
test tests::it_works ... ignored

test result: ok. 0 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running benches/benchmark.rs (target/release/deps/benchmark-194f0cdd6b991aaf)
Gnuplot not found, using plotters backend
fib 20                  time:   [17.858 µs 18.182 µs 18.531 µs]
Found 5 outliers among 100 measurements (5.00%)
  4 (4.00%) high mild
  1 (1.00%) high severe
```

I understand that **the `criterion` will run but show nothing if the `harness` is set to anything other than `true` (including a default value, of course)**.

Anyway, I've resolved this issue. Thanks!

**Comment by AntoniosBarotsis** [comment]
Oh cool, didn't expect that to be honest 😅 

Maybe @jacklund has a similar issue?

**Comment by jacklund** [comment]
Alas, no. I don't have any workspaces, just the one project, and I tried adding the `[[benches]]` section that @Shitaro showed, and got the same result.

Just for more info, here's my directory structure:

```
├── benches
│   └── herding.rs
├── Cargo.lock
├── Cargo.toml
├── files
│   ├── 10.txt
│   ├── 20.txt
│   ├── 25.txt
│   ├── 44.txt
│   ├── 4.txt
│   ├── 6.txt
│   ├── 7.txt
│   └── 8.txt
├── README.md
├── src
│   ├── cbc.rs
│   ├── challenges
        ---more sources
└── target
```
and here's my `Cargo.toml`:
```
[package]
name = "cryptopals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.2"
anyhow = "1.0.68"
asn1 = "0.13.0"
base64 = "0.20.0"
cbc = { version = "0.1.2", features = ["block-padding", "alloc", "std"]}
flate2 = "1.0.25"
hmac = "0.12.1"
iron = "0.6.1"
itertools = "0.10.5"
lazy_static = "1.4.0"
num = "0.4.0"
num-bigint = { version = "0.4.3", features = ["std", "rand"]}
num-modular = { version = "0.5.1", features = ["num-bigint", "std"]}
num-prime = "0.4.3"
openssl = "0.10.45"
params = "0.8.0"
rand = "0.8.5"
rayon = "1.6.1"
reqwest = "0.11.14"
sha2 = "0.10.6"
thiserror = "1.0.38"
tokio = { version = "1.24.2", features = ["rt", "macros"] }
tokio-test = "0.4.2"

[dev-dependencies]
criterion = "0.4.0"
```

Not really sure what I'm doing wrong here.

-Jack

**Comment by AntoniosBarotsis** [comment]
You don't seem to have the `[[bench]]` section. 


Should be something like

```toml
[[bench]]
name = "herding"
harness= false
```

You might also want to include criterion's `html_reports` feature. I'm on my phone right now so double check anything I wrote down for typos 😅

**Comment by jacklund** [comment]
:rofl: So, I _thought_ I'd tried that, but it turns out that I copy-pasta-ed @Shitaro's `barness` typo. :man_facepalming: 

Yep, adding that fixes it. It's weird, because the impression I got from the docs was that you didn't need to do anything but have it in the `benches` dir. Is it maybe because this is a lib crate, not a bin? :man_shrugging: 

Anyway, thanks for the help! Now I just gotta figure out how to make it not get OOM killed when it tries to do the benchmarks (not your problem, my impl probably takes up too much memory).

-Jack

**Comment by AntoniosBarotsis** [comment]
> It's weird, because the impression I got from the docs was that you didn't need to do anything but have it in the benches dir

I've made another issue regarding documentation improvements #638, I am not affiliated with the project in any way but I might eventually make a PR for this. The maintainer has been somewhat inactive for some time now but he might be happier reviewing a PR than replying to issues 😅 

Glad you figured it out! Make sure to close the issue if everything is working fine.
