### ISSUE TITLE
Audit advisory for remove_dir_all, via tempfile

### ISSUE THREAD

**Issue by ZackPierce** [bheisler/criterion.rs#672]
Presently `cargo audit` reveals the following security advisory for criterion.

https://rustsec.org/advisories/RUSTSEC-2023-0018

The root cause is `remove_dir_all`, a transitive dev dependency of criterion via tempfile. 

The audit warning may be trivially cleared up by updating the tempfile dependency to, say, 3.5.  

Per the contributing guidelines, I have not submitted a PR to do so until the maintainers express an interest in fixing this mild security risk.

**Comment by nbarrios1337** [comment]
PR addressing this issue: #675

**Comment by waywardmonkeys** [comment]
This be closed as it was fixed in #675.
