### ISSUE TITLE
The `black_box` function can be replaced with `std::hint::black_box`

### ISSUE THREAD

**Issue by Spartan2909** [bheisler/criterion.rs#700]
The function `std::hint::black_box` is a stable wrapper around the same intrinsic that `test::black_box` uses, and could replace Criterion's own `black_box` function on all release channels. This function has been stable since 1.66, meaning that the last three minor versions of Rust are supported.

**Comment by coolreader18** [comment]
Note that the current black_box implementation actually can lead to an llvm crash: rust-lang/rust#110381
