### ISSUE TITLE
Project does not build due to MSRV

### ISSUE THREAD

**Issue by V0ldek** [bheisler/criterion.rs#728]
The project has an MSRV of 1.64, but the newest clap versions (starting from 4.4.6) require 1.70. This also causes the CI pipeline to fail.

Crietrion should either bump the MSRV as well, or pin clap to 4.4.5 to unbreak the build.

See [relevant `clap` change](https://github.com/clap-rs/clap/commit/d30d94f51c3e10fed96d0a555a0f0c5a2b3a5824).

I wanted to make a PR pinning 4.4.5, but the Contribution guide explicitly says to not submit dep-related PRs.

**Comment by waywardmonkeys** [comment]
I've submitted #731 that fixes this ... let's see what happens.

**Comment by waywardmonkeys** [comment]
@lemmih This can be closed now that #731 has landed.
